### ISSUE TITLE
Stella Glow code doesn't work.

### ISSUE THREAD

**Issue by megagutsman** [FlagBrew/Sharkive#100]
## Issue template

* [ ] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**:00173700
* **Product code**:CTR-P-BS3E
* **Game version**:Latest
* **Luma version**:9.1-89cc6ed

### Not working codes

* Quick Level Up (All Units.)

**Comment by megagutsman** [comment]
Thanks, it worked!

**Comment by JourneyOver** [comment]
> Thanks, it worked!!

As in the code works fine on the latest Luma Nightly? If so please click the button that says close issue.

**Comment by megagutsman** [comment]
Yup, it works like a charm!.
