### ISSUE TITLE
Issue with MHXX cheats version 1.3 

### ISSUE THREAD

**Issue by fiv5e** [FlagBrew/Sharkive#101]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

2317 | Monster Hunter XX: Double Cross | Capcom |   | ja | HR | 32768 | CTR-AGQJ | 0004000000197100 | 7AEB1177 | hr-mhxx | Monster_Hunter_XX_Double_Cross_JPN_3DS-HR | 2367942656 | 11.1.0J | 3DS Game | 1
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Game Info

* **Title ID**: 0004000000197100
* **Game version**: 1.4

### Not working codes
All of them, except for the two ; 

•Produce and upgrading equipment does not need materials v1.3
•Max brave gauge v1.3

the version of the code at the moment is 1.3

**Comment by JourneyOver** [comment]
Is not an issue, as you have already seen ad even mentioned yourself in the issue the codes are made for game version 1.3, while you are running version 1.4 of the game..

Either delete update data and update and stick to 1.3 or figure out how to make codes or 1.4 and send a PR to update codes for 1.4 of the game, or wait till someone else does it.
