### ISSUE TITLE
Pokémon Super Mystery Dungeon report

### ISSUE THREAD

**Issue by Pollolleh** [FlagBrew/Sharkive#103]
* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**: 0004000000174400 
* **Product code**: CTR-P-BPXP
* **Game version**: 1.1.0
* **Luma version**: 9.1-89cc6ed

### Not working codes

* 1st Pokèmon Max Health 
* Infinite PP for 1st Pokèmon

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by Pollolleh** [comment]
Hi, I installed the latest version that you linked and also tested the other codes for Super Mystery Dungeon (when I created the thread I tested only the two that I wrote) and none of those work.

**Comment by JourneyOver** [comment]
Okay thanks, could you do on more thing, if there has been any updates to the game could delete the update data and try the codes on version 1.0 as I have a feeling that the issue is the same as #47

**Comment by Pollolleh** [comment]
They don't seem to work on 1.0 either

**Comment by JourneyOver** [comment]
Alright thanks for the report!

**Comment by Pollolleh** [comment]
Update= Max Exp for 1st Pokèmon does actually work.
