### ISSUE TITLE
M & S at the London 2012 Olympic Games: Cheat does not work

### ISSUE THREAD

**Issue by Adrians1206** [FlagBrew/Sharkive#104]
## Issue template

* [] Issue with Sharkive
* [] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**:0004000000054800
* **Product code**:CTR-P-ACME
* **Game version**:1056 (1.2.0)
* **Luma version**:Luma3DS v9.1

### Not working codes

* code 1  [999 Tickets]
* code 2
* ...

**Comment by JourneyOver** [comment]
Closed due to inactivity.
