### ISSUE TITLE
Contributing Guidlines and Compilation Error

### ISSUE THREAD

**Issue by BSBussell** [FlagBrew/Sharkive#108]
**Not using template because this isn't a code related issue**

I would love to contribute to this project if I could figure out how to compile it, as of now whenever I run the make command on MacOS I get a fatal error:

`/Sharkive/include/common.h:25:10: fatal error: curl/curl.h: No such file or directory`

I tried reinstalling curl with homebrew but nothing changed.
Wondering if anyone has an idea why this is happening and how I can fix it.

**Comment by JourneyOver** [comment]
Since I never had a reason to compile sharkive I'm sadly unable to help, but hopefully Bernardo or another of the flagbrew team will be able to help you out.

// CC @BernardoGiordano could you possibly help him out with this issue?

**Comment by piepie62** [comment]
You need the devkitPro portlibs curl for 3DS, not your distribution's curl

**Comment by JourneyOver** [comment]
Well that would explain it, hopefully it fixes his issue.

@BSBussell if piepies comment helped you out, then please close this issue when you get the chance. :)

**Comment by BSBussell** [comment]
Yes this worked perfectly, thanks for the help, I'd like to know if adding build instructions with at least a link to a guide and instructions to just run make on the readme would be useful
