### ISSUE TITLE
Dragon Quest 8 codes not working

### ISSUE THREAD

**Issue by rebornbubbles** [FlagBrew/Sharkive#112]
## Issue template

* Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**:000400000018F200
* **Product code**:CTR-BQ8
* **Game version**:latest
* **Luma version**:9.1

### Not working codes

* [Skills Points 99]
* [Casino coins]
* [PV 255 for 4 characters]
*[(L+X)MAX Gold v1.0]
*[(L+X)Gold Banked 99999000G v1.0]
*[(L+X)Casino Tokens 99999999 v1.0]
*[(L+X)All members HP999 v1.0]
*[(L+X)All members MP999 v1.0]
*[(L+X)All members skill point999 v1.0]
*[(L+X)All item x950 is in the bag v1.0]
*[(L+X)Monster list complete (All 99999) v1.0]
*[(L+X)Alchemy Recipe Book Complete v1.0]
*[(L+X)Collected Item List Complete v1.0]
*[L+X Unlock All Photo Challenges]

**Comment by rebornbubbles** [comment]
I would like to specify it seems that any code that uses L+X doesnt work the other codes in the db that require button presses seem to work fine: [Camera zoom out(B+L)Enable, (B+R)Disable v1.0].  from what i can tell is that other games with similar codes do not work also

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by rebornbubbles** [comment]
Thank you for the info thats what was needed to fix it
