### ISSUE TITLE
Pokemon all - X/Y, Omega Ruby, Moon, Sun, etc - (EU)

### ISSUE THREAD

**Issue by ImMetatron** [FlagBrew/Sharkive#113]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**: EUR version max upd.
* **Product code**:all pokemon eur
* **Game version**:max upd
* **Luma version**:9.1

### Not working codes

* AP
* HP
* etc
### Note
There is no complete list of codes (some lines are marked with an asterisk and the description is too long to be seen) when using HP / AP recovery codes, the console shuts down with an error. I tried on different series of Pokemon for 3DS / 2DS

Other codes also give an error and do not always work. :-( Only on the Ruby version, I was able to run (money, some items)

p.s.
And where to read the description of the codes? and then some are not clear what they give or their name does not fit into a string on the screen.

**Comment by SpiredMoth** [comment]
Try testing the cheats again with a [nightly build of Luma](https://github.com/hax0kartik/luma-hourlies/releases/latest), which has some fixes to the cheat engine that make some codes work when they previously didn't.

Also make sure that the cheats you test are for the game update version you have installed (i.e. if you have UM v1.2 then do *not* try codes that mention v1.1).

After following the above come back with the results. If you find codes that still don't work then a FlagBrew team member will get around to double-checking and possibly removing the broken code(s).

<br>

As for reading the full cheat names, here are the respective files in Sharkive's DB:
- [X](https://github.com/FlagBrew/Sharkive/blob/master/db/0004000000055D00.txt)
- [Y](https://github.com/FlagBrew/Sharkive/blob/master/db/0004000000055E00.txt)
- [Omega Ruby](https://github.com/FlagBrew/Sharkive/blob/master/db/000400000011C400.txt)
- [Alpha Sapphire](https://github.com/FlagBrew/Sharkive/blob/master/db/000400000011C500.txt)
- [Sun](https://github.com/FlagBrew/Sharkive/blob/master/db/0004000000164800.txt)
- [Moon](https://github.com/FlagBrew/Sharkive/blob/master/db/0004000000175E00.txt)
- [Ultra Sun](https://github.com/FlagBrew/Sharkive/blob/master/db/00040000001B5000.txt)
- [Ultra Moon](https://github.com/FlagBrew/Sharkive/blob/master/db/00040000001B5100.txt)

**Comment by JourneyOver** [comment]
Please do the above, make sure to report any broken codes after. Failure to do so/reply within 7 days will result in a closure of the issue without removal of any broken codes.

Lines marked with an asterisk means the code has a button combo, and sadly we can't do much about lumas cheat menu cutting code descriptions off other than trying to reword descriptions but sometimes that's not always an easy thing to do.

**Comment by JourneyOver** [comment]
Closed due to inactivity.
