### ISSUE TITLE
Sharkive Hangs on Loading screen

### ISSUE THREAD

**Issue by rebeltaz** [FlagBrew/Sharkive#114]
* **Encountered behavior**: Sharkive Hangs on the Loading screen, It never goes past the Please Wait screen and I have to manually shut the system down and back on to get out of it.

**Comment by JourneyOver** [comment]
Where did you download it from? 
are you using the cia version or the 3dsx version? 
how many games do you have on your 3ds?

**Comment by rebeltaz** [comment]
> Where did you download it from?

I downloaded it from here - GitHub.

> are you using the cia version or the 3dsx version?

The cia version.

> how many games do you have on your 3ds?

Wow... I didn't realize I had that many. I just counted them and about 100.

**Comment by rebeltaz** [comment]
Yeah... I didn't wait anywhere near that long. I let it go last night like you suggested and it finally did come up. Thank you!

**Comment by JourneyOver** [comment]
Not a problem at all :)
