### ISSUE TITLE
Ultara Sun cheat

### ISSUE THREAD

**Issue by andree1996** [FlagBrew/Sharkive#115]
I tried to using USUM 1.0 n hit hp never Decrease but the cheat is not working.. my USUM version 1.0

Oh and can u add cheat for Yokai Blasters Red Team and Blue Team too 
Please .

**Comment by SpiredMoth** [comment]
Try testing the cheats again with a [nightly build of Luma](https://github.com/hax0kartik/luma-hourlies/releases/latest), which has some fixes to the cheat engine that make some codes work when they previously didn't.

If the cheat(s) still won't work, let us know and someone will get around to removing them. If you don't respond within 7 days, this issue will be closed for inactivity.

<br>
As for adding codes-- no member of the FlagBrew team currently makes codes, we just keep Sharkive's DB updated with new codes and broken code reports submitted by _other people_. If you want new codes then you'll have to go elsewhere and ask someone who knows how to make them

**Comment by JourneyOver** [comment]
Closed due to inactivity.
