### ISSUE TITLE
Code issue with The Legend of Zelda: Link between Worlds (US)

### ISSUE THREAD

**Issue by AnalogMan151** [FlagBrew/Sharkive#12]
## Issue template

* [X] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**: Show that codes are in DB
* **Encountered behavior**: Shows codes are not in DB after the first initial launch of Sharkdive

### Fill this for problems with codes in the database

* **Title ID**: 000EC300
* **Product code**: CTR-P-BZLE
* **Game version**: v1.0.0

### Not working codes
00040000000EC300

Cheats in red:

Full Hearts
Max Rupees
Max Monster Tails
Max Monster Guts
Max Monster Horns
Max Maimias
Infinite Energy Gauge
Reset Amount of Rupees

Cheats in white:
Invincibility
Skip Lost Woods Puzzle
Instant Text Display

Cheats confirmed working:
Invincibility
Instant Text Display

Unconfirmed or not yet tested:
Skip Lost Woods Puzzle (cheat has a note that does not display in Luma3DS, may want to edit cheat name)

**Comment by JourneyOver** [comment]
Can attest for the 

> Expected behaviour: Show that codes are in DB
> Encountered behavior: Shows codes are not in DB after the first initial launch of Sharkdive

bit as it happens to me as well with various games, one launch it'll show codes are in the DB for a game, next launch it'll show there are no codes in the DB for the same game, happens on multiple games.

**Comment by omega59** [comment]
HI, I tested the codes these do not work.. i can confirm!

Inf. Energy Gauge
skip level lost woods

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by omega59** [comment]
I tried with that Luma built that was suggested, and it did not change anything.
