### ISSUE TITLE
Please update Monster Hunter XX 1.4 database coz i cant find 1.3 update anymore

### ISSUE THREAD

**Issue by cjsales77** [FlagBrew/Sharkive#120]
## Issue template

* [] Issue with Sharkive
* [] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**:
* **Product code**:
* **Game version**:
* **Luma version**:

### Not working codes

* code 1
* code 2
* ...

**Comment by JourneyOver** [comment]
FlagBrew has nobody interested in creating codes right now
