### ISSUE TITLE
3D Classics Xevious Codes Not working

### ISSUE THREAD

**Issue by omega59** [FlagBrew/Sharkive#121]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Should give max lives but does not**:
* **Should give max score but does not**:

### Fill this for problems with codes in the database

* **00054700**:
* **CTR-N-SABE**:
* **Game version**:
* **Luma 9.1-89cc6ed**:

### Not working codes

* Max Lives
* Max Score

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by JourneyOver** [comment]
Closed due to inactivity.
