### ISSUE TITLE
Poochy & Yoshi's Woolly World

### ISSUE THREAD

**Issue by omega59** [FlagBrew/Sharkive#123]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Invisible doesn't work**:

### Fill this for problems with codes in the database

* **001A4100**:
* **CTR-P-AJNE**:
* **Game version**:
* **Luma 9.1-89cc6ed**:

### Not working codes

* Invisibility

**Comment by OGBaggett** [comment]
I think you’re looking at dead software, the developers had been working on this but I believe now they have no way of enabling cheats, per my research through this community. I personally do not use a save editor but it is highly recommended amongst the other members.

**Comment by SpiredMoth** [comment]
Sharkive is *not* dead. Other FlagBrew projects, namely PKSM and Checkpoint, are currently holding our focus. Also there are currently no members of the FlagBrew team who create cheats so all we do with the database are remove reported broken cheats (or relabel them if the game has multiple versions) and add cheats submitted through pull requests.

Accessing cheats to activate them in-game is done through Luma's Rosalina menu (default key combo to bring it up is `L + Down + Select`)

**Comment by omega59** [comment]
Hi thank you for response. I tried the Nightly Luma as suggested and the code is not working.

**Comment by OGBaggett** [comment]
I am sorry for relaying false info, might I have a screenshot of the nightly build

**Comment by JourneyOver** [comment]
So I tested this myself since I have the game, and it works just fine so...Closing this issue as this isn't a broken code.
