### ISSUE TITLE
Outdated Cheats on MHXX

### ISSUE THREAD

**Issue by kylexcore** [FlagBrew/Sharkive#126]
## Issue template

* [] Issue with Sharkive
* [#] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: MONSTER HUNTER XX
* **Product code**:
* **Game version**: JAP
* **Luma version**: B9S

### Not working codes

* ALL CHEATCODES NOT WORKING DUE TO OUT DATED CODES PLEASE UPDATE TO 1.4 THANKS

**Comment by JourneyOver** [comment]
FlagBrew does not currently have a person capable of creating codes. If we did, then we would update the codes. If you are able to find/create codes that work for the latest version you are free to either submit a PR with said updated codes, or if you find codes for the 1.4 then you can throw up a link and I will update the codes when I can.
