### ISSUE TITLE
Sharkive Cheats

### ISSUE THREAD

**Issue by RJWJ186** [FlagBrew/Sharkive#128]
## Issue template
I was trying to use cheats in a game called "Yo-Kai Watch", but when I tried one of the cheats it either wouldn't work or crashed. 
* [] Issue with Sharkive
* [] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**:
* **Product code**:
* **Game version**:
* **Luma version**:

### Not working codes

* code 1
* code 2
* ...

**Comment by JourneyOver** [comment]
Please fill out the issue form, once you have done this then feel free to re-open this issue.
