### ISSUE TITLE
Yo-kai Watch Cheats Not Working

### ISSUE THREAD

**Issue by RJWJ186** [FlagBrew/Sharkive#129]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: Yo-kai Watch USA
* **Product code**: Usa
* **Game version**: 1.2
* **Luma version**: v9.1-4b341e03

### Not working codes

* code 1 All codes
* code 2
* ...

**Comment by JourneyOver** [comment]
I can not find that commit number for luma, so please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by piepie62** [comment]
He is running Nanquitas's fork of Luma

**Comment by JourneyOver** [comment]
Ah got it, I never really checked on commit numbers for Nanquitas's fork so no wonder I didn't recognize it xD anyways guess I'll mark this as `WIP` now so I can remember to remove the codes when I have time since it seems all of them are broken *due to the fact that he made a issue in my repository as well for the same game.

**Comment by RJWJ186** [comment]
Thank you.

**Comment by SpiredMoth** [comment]
Considering that none of the codes mention a version, my guess is that they're not broken just outdated

**Comment by JourneyOver** [comment]
I don't have the game nor my 3DS around to test the codes myself right now, so if @RJWJ186 wants to test the codes on an older version of the game then it'd be nice to figure out before I completely remove the codes.

**Comment by RJWJ186** [comment]
I just tried it with the first version, it works now.

**Comment by JourneyOver** [comment]
@RJWJ186 	thanks for testing, will update the codes to mention they are for 1.0 then for both my repository and this repository whenever I have time to sit down and do so.
