### ISSUE TITLE
Code issue: Pokemon Alpha Sapphire 1.4 (EUR)

### ISSUE THREAD

**Issue by VaporMoon** [FlagBrew/Sharkive#131]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 000400000011C500
* **Product code**: CTR-P-ECLA
* **Game version**: 1.4 (EUR)
* **Luma version**: 92-luma3ds-1c7b55e

### Not working codes

* [Walk&run Speed x2 v1.4] - Causes a system crash, can provide the dmps if requested
* [(Hold R)Walkthrough Wall v1.4]
* [Egg Instant Hatch v1.4]
* [100%Catch 1.4]
* [Catch Trainer's Pokemon v1.4]
* [(START+L)Wild Pokemon Shiny, (START+R)Disable v1.4]
* 

### Unstable
* [Instant Messages v1.4] - The code works but it causes a system crash 90% of the time when during a screen transition.
* [Access the PC from anywhere v1.4] - It enabled fine but I couldn't figure out how to actually access the PC and then it caused a system crash on screen transition 

Codes tried by themselves with no others active at the same time.

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by VaporMoon** [comment]
I am using the latest Luma nightly as my original message states.

**Comment by JourneyOver** [comment]
Sorry was in a rush when I looked through this and completely missed the `1c7b55e` but, will mark it as WIP and get to it when I can.

BTW the `Product code` you can find this info on sharkive, it's the thing that starts with `CTR`
