### ISSUE TITLE
No cheats for New Super Mario Bros 2 Special Edition

### ISSUE THREAD

**Issue by Manfr3** [FlagBrew/Sharkive#132]
There aren't cheats for New Super Mario Bros. 2 SE (EUR), can you add it?

**Comment by JourneyOver** [comment]
FlagBrew does not currently have a person capable of creating codes. If we did, then they would show up in Sharkive. If you are able to find/create codes that work you are free to either submit a PR with said updated codes, or if you find codes then you can throw up a link and I will update the codes when I can.

**Comment by iGom** [comment]
https://github.com/KimDebroye/N3DS-Cheat-Codes

**Comment by GriffinG1** [comment]
@iGom this issue has been closed for 9 months. Please do not post on outdated issues. You are free to PR those codes if they work. @piepie62 can you please lock this issue.
