### ISSUE TITLE
Puzzles and Dragons Z code is missing some content to be "ALL items"

### ISSUE THREAD

**Issue by deadmanbomber** [FlagBrew/Sharkive#133]
I have just tried out the Puzzles and dragons Z all eggs code and all runes/relics code, hoping to get the event distribution eggs, special holiday eggs, and all event runes, only to find that they were missing. Same thing with the runes and relics. The event runes and relics are missing, except the ones I scanned via orb code.

**Comment by deadmanbomber** [comment]
I will evolve and fill as much of the monster dex as I can so I can screenshot the missing creatures and runes/relics

**Comment by deadmanbomber** [comment]
Just to add, not every egg is even present. The King dragon eggs, Normal Dragon eggs, Mega eggs, the earth knight egg, namero egg, blue fafnir, are missing, as far as I know. I have yet to beat the game and obtain every egg, that is if there is eggs missing.

**Comment by JourneyOver** [comment]
Unless you can find a code that is up to date and works that adds everything that is missing to the "All Items" code, then idk what to really say (other than of course closing this issue) as we have no one in the team who makes codes, and I don't know enough about the game really to look into finding the code myself (not that I really have time to anyways as I'm in the middle of a move and all that atm).

**Comment by deadmanbomber** [comment]
Ok. I don't know how to make a code myself, but I can try to figure it out.
