### ISSUE TITLE
Mario Kart 7 codes are not working

### ISSUE THREAD

**Issue by deadmanbomber** [FlagBrew/Sharkive#135]
* Issue with one or more codes in the database

* **Title ID**: 0004000000030800
* **Product code**: 
* **Game version**: 1.1
* **Luma version**: 9.1

### Not working codes
Drunk driving
Infinite speed boosts (rev1)

Unknown if it works or not, for no instructions are giving on how to use them
*Gravity modifier
*water everywhere
*boost speed modifier
*position modifier

I have to go to work and will keep testing more codes when I come back. I don't actually know if a digital copy can be affected differently than a physical cartridge, so that could be tested. I don't know where I find my product code. I am trying to follow the template this time. I did see that there was several other posts already, links to the past issues below.
1) [https://github.com/FlagBrew/Sharkive/issues/49](url)
2) [https://github.com/FlagBrew/Sharkive/issues/9](url)
3) [https://github.com/FlagBrew/Sharkive/issues/16](url)
4) [https://github.com/FlagBrew/Sharkive/issues/99](url)

**Comment by JourneyOver** [comment]
since you had already noted that you tested with the luma nightly in another post I'll just mark this as WIP until I can get around to doing this issue.

**Comment by JourneyOver** [comment]
Issue has been taken care of
