### ISSUE TITLE
An idea that might not work, but would be useful for portable code editing (Enchancement label here)

### ISSUE THREAD

**Issue by deadmanbomber** [FlagBrew/Sharkive#136]
Idea: the ability to make/modify a gate shark code on the go, without the hassle of needing emulator or a device besides the 3DS to edit code.

Of course, you will need a PC/laptop to even get the option to hack the 3DS, but let's say you accidentally dropped you laptop, or the PC broke down. This could be useful for fixing/creating codes on the fly. It will probably be difficult, but it could potentially help developers make codes and save time. I don't know if this will work at all or not, but it's just an idea. It will most likely have to be integrated into LUMA, but just an idea. Would also be helpful for developers who cannot handle CITRA on their PC. This is just an idea, you don't have to add it.

Note (I don't know how to add labels, so just add the enhancement label here. I also don't know where to put this, so I put this here)

**Comment by JourneyOver** [comment]
There's already things like this for the 3DS, through the means of CTRPF and the action replay code editor which you can find here https://gbatemp.net/threads/ctrpluginframework-blank-plugin-now-with-action-replay.487729/ There is even a video on the page that goes through the process of creating a cheat.
