### ISSUE TITLE
Codes Not Copying

### ISSUE THREAD

**Issue by aeridus** [FlagBrew/Sharkive#146]
## Issue template

* [*] Issue with Sharkive
* [] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
When I hit A on games, the codes should copy from DB to SD.
* **Encountered behavior**:
When I hit A on some games, the codes don't copy from DB to SD. So far I've seen it happen with Mario Kart 7 and WarioWare Gold.

### Fill this for problems with codes in the database

* **Title ID and Product code**:
Mario Kart 7, ID 00030800, CTR-P-AMKE
WarioWare Gold, ID 001D1C00, CTR-P-AWXA
* **Luma version**:
9.1

**Comment by JourneyOver** [comment]
one of the many known issues that will be fixed once sharkive is integrated into checkpoint.
