### ISSUE TITLE
Mario & Luigi Bowserinside story EUR 3ds crash or don't work

### ISSUE THREAD

**Issue by zFerry98** [FlagBrew/Sharkive#151]
Codes don't work (EUR version), sometimes crash.

3DS
00040000001D1500
CTR-P-A3RP
Game version 1.2
Luma 9.1

### Not working codes

All

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by zFerry98** [comment]
Luma 9.1-2c8a1eb5

Same thing, both v1.1 and v1.0 (don't work or crash).
I go directly to the save-editor.
Thanks anyway.

**Comment by JourneyOver** [comment]
Well that's the issue there, I didn't even check what codes where available last night when I asked you to re-test the codes with the latest luma nightly.. All codes are for 1.1 and 1.0 of the game while you are running 1.2 so obviously the codes will not work (and possibly crash).

If you downgrade the game then you should be able to use the codes.
