### ISSUE TITLE
Kirby epic yarn code don't work

### ISSUE THREAD

**Issue by omega59** [FlagBrew/Sharkive#153]
## Issue template

* X[] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **3DS:
* 001d1e00****:
* **Ctr p be4e**:
* * Original**:
* **9.1**:
* **Atmosphere-NX version**:
6423d0c1

### Not working code 
instant 9999 beads in level.

**Comment by JourneyOver** [comment]
Even though you completely butchered the template, I am going to let it slide this once since I know what TitleID this issue is for, I am going to be testing the code myself when I can get time to make sure this code is actually broken or not before I end up removing it.

**Comment by omega59** [comment]
Sorry I'm on mobile and I may have had difficulty typing and editing the text.
