### ISSUE TITLE
Pokemon alpha sapphire cheats not working at all

### ISSUE THREAD

**Issue by jeremeng** [FlagBrew/Sharkive#155]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

Platform (3DS/Switch): 3DS
Title ID: 000400000011C500
Product code:
Game version: 3.0.0
Luma version: 9.1
Atmosphere-NX version:
im using any nightly luma update i think
Not working codes
i cant use most off the cheat codes in game at all , can you help me why i cant the use the games cheats at all. my 3DS crash when i try to use the cheats
thanks before

**Comment by JourneyOver** [comment]
`Game version: 3.0.0` is not correct, I need to know your version of the game. like 1.0, 1.1, etc, as there is no version 3.0 of PKMN:AS.

Also please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, and when you report back to this please write down the codes that don't work. Saying `i cant use most off the cheat codes in game at all` does not help me out in removing any bad codes in the slightest.

**Comment by JourneyOver** [comment]
Closed due to inactivity.
