### ISSUE TITLE
Trouble Using Fire Emblem Fates [Select+Y] and "Forge +7" Cheats

### ISSUE THREAD

**Issue by rebeltaz** [FlagBrew/Sharkive#156]
## Issue template

* When ever I activate any of the [Select+Y] cheats in Rosalina for *Fire Emblem Fates* and then try to use that cheat (I assume correctly) by pressing [Select] and [Y] together, nothings happens. If I happen to also have [All Weapons Forged +7] enabled (which does not seem to do anything either, btw), the system will crash when I press [Select] and [Y].

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 0004000000179800
* **Product code**: CTR-P-BFZE
* **Game version**: ???
* **Luma version**: v9.1
* **Atmosphere-NX version**: ???

### Not working codes

* any [Select+Y] code
* All Weapons Forged + 7

**Comment by JourneyOver** [comment]
Couple things I need to know.

1. I need to know your game version [example 1.0, 1.1, 1.2, etc..] as I look around on certain sites it seems there was an update for the game at one point or another.

2. Are you running any patches like Same Sex Marriage/Corrinsexual Rebalancing Patch/undub or any others.. ( I dunno if this could cause any issues or not with cheats tbh but there is always a possibility so we only support games as they are intended to be)

3. Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. 

Failing to reply within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by rebeltaz** [comment]
I really don't know what the version of the game is or how to find it. In FBI, I found I actually have two entries for "Fire Emblem Fates" - ID# 004000000179800 and 0004008c00179400. FBI shows these to be version 0 (0.0.0.) and 272 (0.17.) respectively. I don't think I have any patches applied to this game, but I do have the DLC pack installed. 

I'll try the Luma nightly and report back.

**Comment by JourneyOver** [comment]
Since you have two different entries in FBI, going to have to ask if one of the icons have a layer on it that says either V or version with a number after it?

**Comment by SpiredMoth** [comment]
The beginning of the title ID determines what kind of title it is:
- `00040000` is a title (game)
- `00040002` is a demo
- `0004000E` is a title update
- `0004008C` is DLC

**Comment by JourneyOver** [comment]
Ah did not know that. Well then all I am waiting for then is just him to get back to me on if luma nightly made the codes work for him or not.

**Comment by rebeltaz** [comment]
OK... to answer your last question, no... there is no v.?? on the icon like I see on a couple of other games, so I guess it's not be updated?

I installed the nightly last night and re-ran the codes. The [Select+Y] codes did work, but... only if the "All Weapons Forged +7" is not active. If it is, that still doesn't seem to do anything and as long as that one is active, pressing [Select] and [Y] still causes the system to crash.

**Comment by JourneyOver** [comment]
okay well I removed the code "All Weapons Forged +7" in the latest commit, so it should no longer be present, gotta remind myself not to do commits on my webbrowser now as it messed up my commit message >.>

anyways commit https://github.com/FlagBrew/Sharkive/commit/2caf258b95b0ee8c3caf6f74a9614dfd3eaf867a closes this!
