### ISSUE TITLE
Help Modifying Pokemon crystal Code

### ISSUE THREAD

**Issue by derangedsnowman2** [FlagBrew/Sharkive#172]
[Happiness/Egg Hatch Time Modifier, Party Slot 1]
08A31CA6 00000008

This code only lowers happiness to 0.
I cannot figure out what part to modify to make happiness max. Please help.

**Comment by JourneyOver** [comment]
FlagBrew does not currently have a person capable of creating codes, so therefor we have no one who knows what to really change to be able to help with your question. This is better off being asked somewhere else like gbatemp or something.
