### ISSUE TITLE
Pokémon Rumble World Not working codes report

### ISSUE THREAD

**Issue by LePetitMage** [FlagBrew/Sharkive#173]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 0004000000164600
* **Product code**: CTR-N-KCFA
* **Game version**: 1.1.0
* **Luma version**: 10.0.1
* **Atmosphere-NX version**:

### Not working codes

* code 1 : 900k P
* code 2 : 500 D
* code 3 : 100 crowns

**Comment by JourneyOver** [comment]
@hexthat 	can you please chime in on this issue? As you are the one who created the PR for `0004000000164600` do the codes only work for a specific version or?

**Comment by JourneyOver** [comment]
27 days and no word from @hexthat 	dunno what I'm going to do about this issue yet as I currently no longer have a way to test codes myself, and I don't know if hex created the codes or got them from somewhere else tbh as searching around hasn't really produced any results.

**Comment by JourneyOver** [comment]
I'm going to go ahead and close this as I haven't heard from @hexthat , if the issue comes up again with these codes not working then I will remove them.
