### ISSUE TITLE
Crashes / Forced Closure

### ISSUE THREAD

**Issue by Marc2346** [FlagBrew/Sharkive#177]
The first time I can start it and I don't get any cheat. Restarting it now crashes and the closure is forced...
Any solution?

PD: Im Spanish, srry 4 my bad english xd

**Comment by FM1337** [comment]
Sharkive is no longer supported, please use the latest version of [Checkpoint](https://github.com/FlagBrew/Checkpoint)

**Comment by GriffinG1** [comment]
Sharkive is solely a database for cheats now. Install [Checkpoint](https://github.com/FlagBrew/Checkpoint/releases) as it's been merged into it
