### ISSUE TITLE
3ds sharkive crashes after the initial load on sharkive

### ISSUE THREAD

**Issue by Storm-Surfer7** [FlagBrew/Sharkive#178]
Whenever i boot into the sharkive application it initially works and then gets to the sharkive please wait screen and then crashes. is there any possible reason? Console: O3dsXL Luma3ds ver: 11.0.1 3ds' firmware: 11.11.0-43 Eur

**Comment by piepie62** [comment]
Sharkive as an application is discontinued. Please use Checkpoint instead

**Comment by Storm-Surfer7** [comment]
bc i can't figure out how to add cheats using checkpoint and sharkive was the only method i knew
:/

**Comment by GriffinG1** [comment]
https://www.youtube.com/watch?v=o7mdfoZbJE0 Go watch this.

**Comment by Storm-Surfer7** [comment]
it works now, thanks!
