### ISSUE TITLE
[Pokemon Y] Faulty Cheat

### ISSUE THREAD

**Issue by RunicAce** [FlagBrew/Sharkive#180]
## Issue template

* [Crash] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 00055E00
* **Product code**: CTR-P-EK2A
* **Game version**: 1.5
* **Luma version**: 10.0.1

### Not working codes

* Hold L to view IVs & hold R to view EVs on Pokemon Status screen

[Crash dump](https://ufile.io/9qzhvpyq)

**Comment by JourneyOver** [comment]
Since it's a crash and not just a \*not working code\* means that it's more than likely a kernal bug which is not fixable, code may be fine. I'm going to close this, if the same code gets reported again, then I will remove it.
