### ISSUE TITLE
Dragonball xenoverse 2 codes are no longer working on the new version update

### ISSUE THREAD

**Issue by danver2** [FlagBrew/Sharkive#182]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**:Switch
* **Title ID**:010078D00F88000
* **Product code**:
* **Game version**:ver1.12.02
* **Luma version**:
* **Atmosphere-NX version**0.94
### Not working codes

* 100,000,000 zennie
* 100,000,000 tp
* ...

**Comment by JourneyOver** [comment]
Can you tell me the previous version that the codes was last working on for you by chance?

*gathering that it worked for you on a previous version due to how you worded the issue.

**Comment by danver2** [comment]
the codes that worked for me was for breath of the wild but now not even those are working

**Comment by JourneyOver** [comment]
So your saying codes work for you one moment and then don't work the next? even on the same version of the game?

**Comment by danver2** [comment]
for a different game yes

**Comment by danver2** [comment]
i could not get it to work for xenoverse 2 but for once i got it to work for zelda breath of the wild but only once

**Comment by JourneyOver** [comment]
Did xenoverse 2 work on an older version for you? as you said that "are no longer working" in the issue title which sounds like you had it working and then maybe updated the game and it stopped working..

I can't say much for BOTW, other than it could be because of the codes maybe for an older version of the game as well. It all depends on if you had codes working and then updated said games and then they stopped working.

and I sadly can't test cheats for switch games myself due to the fact that I don't have a hackable switch, so I have to make get every detail I can from whoever makes an issue for switch cheats before I decide on the next course of action.

**Comment by danver2** [comment]
no this is the first time i tried doing this with xenoverse 2 and had the latest version and it never worked

**Comment by danver2** [comment]
would also be nice if someone could give me like a step by step list on wtf i am supposed to do because i am not sure if i am even doing this right anymore

**Comment by JourneyOver** [comment]
Hmm alright, do you mind testing a lower version of the game by chance for xeno 2? I'm also going to be MIA for a bit while I wait on my RMA for my motherboard for my new computer , so I may not get back to this issue until then.

**Comment by danver2** [comment]
just a question how do i lower the game version since i am on the latest version of switch?

**Comment by JourneyOver** [comment]
not fully sure tbh as I haven't had a need to do it myself, could probably do it in the system settings somewhere though.

**Comment by danver2** [comment]
ok btw i was able to get the codes for zelda to work again and found what i was doing wrong

**Comment by danver2** [comment]
so instead of saving the codes then going back in then hit the plus button then close the game and reopen it i would just select the codes then hit the home button then close the game

**Comment by danver2** [comment]
but the xenoverse 2 codes still wont work though

**Comment by JourneyOver** [comment]
Like I said before it could be a version difference on why they won't work for you, I couldn't really say though unless someone on an older version said something. I'll just remove the codes whenever I get my computer back up and running again in a few weeks.

**Comment by danver2** [comment]
ok np

**Comment by AHRI0048** [comment]
Ahhh can i ask something i new on this
Why my sharkive still going back on home if i open it?

**Comment by GriffinG1** [comment]
don't ask questions on random, unrelated issues. look at #179 @AHRI0048.

**Comment by danver2** [comment]
dude what are you talking about this is not random at all or unrelated
