### ISSUE TITLE
Sharkive randomly started force closing. HELP!

### ISSUE THREAD

**Issue by SonicFuture87** [FlagBrew/Sharkive#183]
Sharkive started crashing after the loading screen...I'm not sure what I did. I keep reading that I have to download checkpoint but that's already installed it has nothing to do with sharkive as far as I'm concerned. HELP PLEASE. I'd like to continue downloading cheats. I'd hate to start doing it manually.

**Comment by GriffinG1** [comment]
Look at the pinned issue.

**Comment by SonicFuture87** [comment]
Hello?! why was my issue closed? And the similar issue before that got
closed as well? Is there something I'm missing?
