### ISSUE TITLE
STOP CLOSING THIS ISSUE!!!

### ISSUE THREAD

**Issue by SonicFuture87** [FlagBrew/Sharkive#185]
SHARKIVE IS NOT WORKING
I NEED SOME HELP

**Comment by SpiredMoth** [comment]
See https://github.com/FlagBrew/Sharkive/issues/179#issuecomment-533768841

**Comment by BernardoGiordano** [comment]
Sharkive is deprecated. Use checkpoint instead of it. Also, please don't spam the issue tracker.
