### ISSUE TITLE
Code not working for Super Pokemon Rumble

### ISSUE THREAD

**Issue by OmeletteDuFromage07** [FlagBrew/Sharkive#190]
Issue with one code in the database

* Platform : 3DS
* Title ID : 0004000000066D00
* Product code : CTR-P-ACCP
* Game Version : 0 (0.0.0)
* Luma version : 9.1
* Atmosphere-NX version : Idk
### Not working codes

* code 1 (infinite money)

**Comment by JourneyOver** [comment]
Hello,

Please update your luma version to the latest version and test the codes again. You are running an outdated version of luma that has bugs with cheat compatibility, while the latest version of luma fixes various cheat compatibilities.

If the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of any broken codes. 

Thank you!

**Comment by OmeletteDuFromage07** [comment]
> Hello,
> Please update your luma version to the latest version and test the codes again. You are running an outdated version of luma that has bugs with cheat compatibility, while the latest version of luma fixes various cheat compatibilities.
> If the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of any broken codes.
> Thank you!

Thanks, i Don't even know why i tried everything, but didn't even think about updating luma.. ^^'
Btw i just did it, but now, when i launch the game, it says "No cheats found for title 000400000066D00".. Do you know what's my mistake ? :/

Thanks !

**Comment by JourneyOver** [comment]
No idea, all I could say is try to download the cheats again or something. Maybe you deleted them somehow on accident.

**Comment by OmeletteDuFromage07** [comment]
Did this, and the codes still Don't work for me..
