### ISSUE TITLE
Pokémon Let's Go Pikachu Cheats don't work

### ISSUE THREAD

**Issue by CoughingCat** [FlagBrew/Sharkive#191]
* **Platform**: Switch
* **Title ID**: 010003F003A34000
* **Game version**: 1.0.2
* **Atmosphere-NX version**: 0.9.4 (c62c484)
* **Not working codes**: All Codes

**Comment by BernardoGiordano** [comment]
It's not that they don't work, they're just for a different version than yours

**Comment by CoughingCat** [comment]
Oh ok.  How can I find out for which version the cheats are?  Because they are still displayed to me anyway.
