### ISSUE TITLE
Pokemon Let's Go: Eevee & Pokemon Let's Go: Pikachu (Out of Date)

### ISSUE THREAD

**Issue by Th3Alic3** [FlagBrew/Sharkive#193]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: Switch
* **Title ID**: Pokémon Let's Go: Eevee & Pikachu
* **Product code**: 0100187003A36000 (listed Eevee ~ couldn't find Pikachu's)
* **Game version**: v1.0.1 & v1.0.2
* **Atmosphere-NX version**: Latest

### Not working codes: ALL!

Hello,

The Let's Go games received a game update nearly half a year ago. The current codes in the database for v1.0.0 and v1.0.1:
- "Sharkive/switch/0100187003A36000/0a3f0d21e67dad80.txt"
- "Sharkive/switch/0100187003A36000/dcd187e409188ab1.txt"

The codes for neither v1.0.0 nor v1.0.1 are not labelled to clearly indicate which version of the game the codes are intended for.

> For example: in the Sharkhive database the codes for Super Mario Odyssey are labelled to accommodate the game's single update. The v1.2.0 update is clearly labeled in the Sharkhive database to allow players to know which version to use: Sharkive/switch/0100000000010000/f5dccddb37e97724.txt

1. Would you please add version v1.0.2 to your database?
2. Would you please amend the codes for ALL three versions to indicate which version of the game they work with: v1.0.0, v1.0.1, or v1.0.2?
3.) Would you add a codes to v1.0.2 to parallel all the codes found under v1.0.1?
4.) Would repeat the same for Let's Go: Pikachu

Thanks

**Comment by JourneyOver** [comment]
> Would you please add version v1.0.2 to your database?
> Would you add a codes to v1.0.2 to parallel all the codes found under v1.0.1?
> Would repeat the same for Let's Go: Pikachu

FlagBrew does not currently have a person capable of creating codes. If we did, then we would update the codes. If you are able to find/create codes that work for the latest version you are free to either submit a PR with said updated codes, or you can throw up a link to someone who has made codes for the latest version and I will update the codes when I can.

> Would you please amend the codes for ALL three versions to indicate which version of the game they work with: v1.0.0, v1.0.1, or v1.0.2?

This I can do, not every game for the switch side of the database has their versions labeled fully due to the fact that the initial location the database came from didn't have them either, but they will get added over time. (it's pretty much the same on the 3DS side as well)

**Comment by Th3Alic3** [comment]
> FlagBrew does not currently have a person capable of creating codes. If we did, then we would update the codes. If you are able to find/create codes that work for the latest version you are free to either submit a PR with said updated codes, or you can throw up a link to someone who has made codes for the latest version and I will update the codes when I can.

Is there a Discord Group started for FlagBrew? I would happily start to coordinate pushing things forward. It is not enough for a single soul to trying make progress - it takes people... a community. Discord is the most logical location to cultivate it.

**Comment by piepie62** [comment]
Yes, we have a [Discord server](https://discord.gg/bGKEyfY).

**Comment by GriffinG1** [comment]
Nobody on FlagBrew is interested in making them either. The discord is [here](https://discord.gg/bGKEyfY) and also linked in the repo description.

**Comment by Th3Alic3** [comment]
No wonder. There is no dedicated group and set of channels devoted to Sharkhive. A single "general chat" cultivates nothing.

**Comment by GriffinG1** [comment]
Again, nobody on FlagBrew is interested in learning to make them. Sharkive is solely a database, and more than one channel is not necessary. As Journey said above, PRs are accepted, so you're free to PR any codes you find/make.
