### ISSUE TITLE
Cheat Crashing on a title (ARM11) 3DS/2DS XL

### ISSUE THREAD

**Issue by Whynotboi** [FlagBrew/Sharkive#199]
## Cheats not working, crashes the system
Error Message displays:
**Arm11
Data Abort
Translation-Section
Remillio (00040000001d1400)**
* Issue with every code for this title only
* *New 2ds XL**:
* **00040000001d1400**:
* **Mario & Luigi: Bowser's Inside Story + Bowser Jr's Journey**
* **CTR-P-A3RE**:
* **0.0.0**:
* **10.0.1**:
Better description:
I seriously don't understand, it is not working and I need some help
I tried cheats on Sonic Generations and it worked, I backed up save data and redownloaded the title, I tried seeing if I renamed the stored cheat file to the update ticket for it and it still didn't work... I searched everywhere for an answer for this but no one seems to have this same problem...

[Screenshots]
(![HNI_0055](https://user-images.githubusercontent.com/60987968/74389658-e7739400-4dcc-11ea-90ea-16fc9998b826.JPG)
[)
[![HNI_0054](https://user-images.githubusercontent.com/60987968/74389656-e6dafd80-4dcc-11ea-9b14-58d7f4532085.JPG)](url)

**Comment by Whynotboi** [comment]
Well, I reopened, if you need more specifics I can get some things done within a day... Such as the crash dump file from Luma, or anything really specific, I can **try** to get those... it might take a day, I can ask my friend to lend his SD card with a micro SD slot for the crash dump. I'm just trying to get my cheats working for me and anyone else who has this problem, thank you.

**Comment by JourneyOver** [comment]
You're probably running into:

```
This is due to a kernel bug. Luma's cheat engine would need to be redesigned to fix this, which would cause another bug elsewhere. As such, there is no solution to this problem at this time besides using another console.
```

**Comment by Whynotboi** [comment]
Alrigh

> You're probably running into:
> 
> > This is due to a kernel bug. Luma's cheat engine would need to be redesigned to fix this, which would cause another bug elsewhere. As such, there is no solution to this problem at this time besides using another console.
> 
> or you are selecting codes that are possibly for a older version of the game.

Alright...
