### ISSUE TITLE
cheat red Text

### ISSUE THREAD

**Issue by Nozk** [FlagBrew/Sharkive#204]
## Issue template

* [] Red Text with various cheats

### Fill this for problems with codes in the database

* **Platform (3DS)**:
* **Pokemon:Ultra Moon**:
* **00040000001B5100**:
* **1.2**:
* **10.0.1**:
* **unsure**:

### Not working codes

* [HP Not Decrease v1.2]
* [Always critical hit v1.2]
* [No Encounter, Hold START Instant Encounter v1.1 & v1.2]

**Comment by ThoughtVomit** [comment]
I've had the same issue with those cheats, Also the [PP Not Decrease v1.2].

**Comment by GriffinG1** [comment]
From the README:
![9846A2AC-A778-4146-976A-5D2C3C45868E](https://user-images.githubusercontent.com/28538707/77807245-e0d37000-704c-11ea-9dd3-51456fc048b4.jpeg)

Please verify that you have taken these steps

**Comment by JourneyOver** [comment]
Thank you @GriffinG1 :) I've been pretty busy with irl stuff so I just haven't really been able to keep up with issues and all that with the database right now :/
