### ISSUE TITLE
Issue in MHXX ver 1.4

### ISSUE THREAD

**Issue by Smashboi04** [FlagBrew/Sharkive#206]
**Issue In MHXX ver 1.4**

* [] When using a cheat code it turns red and the cheats are from the old version, and there's many duplicated cheats.

### Fill this for problems with codes in the database

* **Platform**:3DS
* **Title ID**: 0004000000197100
* **Product code (main game)**:CTR-P-AGQJ
**Product code of the update(Ver1.4 MHXX)**:CTR-U-AGQJ
* **Game version**: Ver 1.4
* **Luma version**:10.0.1

###Not working code

* Some of the code are working like 3-5 code are working but all of them turns red when selected.

**### I Need Help!**

* can somebody update the cheats in checkpoint?
* and can anyone can send me a txt cheat file with all the cheat version 1.4

Thank you!

**Comment by GriffinG1** [comment]
Both from the readme:
![5AAB36E1-8766-4A34-8650-41243272CDCE](https://user-images.githubusercontent.com/28538707/77878087-b2a08c80-7214-11ea-9598-ac19b61377ea.jpeg)
![44CE5917-2EA8-45D6-981A-EA02D98A7EB6](https://user-images.githubusercontent.com/28538707/77878089-b3d1b980-7214-11ea-881c-85ef54261a87.jpeg)

**Comment by JourneyOver** [comment]
You're running version 1.4 of the game (which currently there are no cheats in the database for 1.4 at all), either downgrade to an older version of the game (versions 1.0, 1.1, 1.2 have lots of codes) or you could try to find new codes and make a PR like GriffinG has pointed out.

Closing this as this is an issue to do more so with you running a version of the game that is higher than the codes we have currently are made for.
