### ISSUE TITLE
Bravely Default cheat codes for refill TP have the wrong hex value

### ISSUE THREAD

**Issue by poppy10** [FlagBrew/Sharkive#207]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **3DS**:
* **00040000000FC500**:
* **00040000000FC500**:
* **1**:
* **Luma version 10.0.0.1**:

### Not working codes
The "refill TP" codes only refill 999, when they should refill 9999 (as the maximum TP is 9999, not 999 unlike for the MP codes). To correct this, the hexadecimal 000003E7 in all four of the following codes should be replaced with 0000270F. I have verified this change as working on my 3DS.

* code 1
[Max TP Agnes]
080ABAF0 000003E7 (should be 080ABAF0 0000270F)

* code 2
[Max TP Ringabell]
080AF9DC 000003E7 (should be 080AF9DC 0000270F)

* code 3
[Max TP Edea]
080B38C8 000003E7 (should be 080B38C8  0000270F)

* code 4
[Max TP Tiz]
080A7C04 000003E7 (should be 080A7C04  0000270F)

**Comment by poppy10** [comment]
The same _should_ apply for the EUR version of this game (00040000000FC600) but as I don't own that one I can't personally verify

**Comment by JourneyOver** [comment]
Will get this fixed when I have time. Thanks for the report.
