### ISSUE TITLE
Sharkive's title scanner not refreshing titles properly

### ISSUE THREAD

**Issue by Shabbypenguin** [FlagBrew/Sharkive#21]
## Issue template

* [x] Issue with Sharkive
* [] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* Load up sharkhive and see all installed titles
* Sharkive loads up and detects some titles, but others refuse to show

### Not working games

Yoshi's Wooly World - CTR-N-AJNE
Link Between Worlds - CTR-N-BZLE
Mighty Gunvolt Burst - CTR-N-J2VE
Pokemon Crystal - CTR-N-QBRA
Virtue's Last Reward - CTR-N-AKGE
Zero Time Dilemma - CTR-N-BZEE
Mario Party Island Tour - CTR-N-ATSE
Layton Miracle Mask - CTR-N-AKKE
Layton the Azran Legacy - CTR-N-AL6E
Zelda Four Swords - TWL-N-KQ9E
Zelda Majora's Mask - CTR-N-AJRE
Team Kirby Clash Deluxe - CTR-N-JLKE
Pokemon Gold VC - CTR-N-QBPA
Metal Gear Solid 3 - CTR-N-AMGE

## Information

Loading up sharkive shows 21 games installed and the above games do not show even with a hard reboot.

**Comment by ValliantStorme** [comment]
Had you saved in those games before installing Sharkive for the first time?

**Comment by Shabbypenguin** [comment]
Games were installed but hadnt been launched yet/gamesaves before sharkive was launched for the first time.

deleting titles.sha from the sharkive folder on the sdcard forced sharkive to rescan the games and now all of them appear. it appears sharkive isn't scanning for new games as intended.

**Comment by JourneyOver** [comment]
@BSBussell sharkive will eventually get an update that fixes this issue and other small issues, but sharkive is currently on the low end of the spectrum right now what with the PKSM rewrite going on and such as noted [here](https://github.com/FlagBrew/Sharkive#todo)

**Comment by darkt6** [comment]
I am having the same issues with numerous other games. I have had them loaded and I uninstalled and then reinstalled thinking that that could solve the problem but that did not work.
Animal Crossing usa 1.5
Zelda OoT
LM dark moon
pkmn silver
pkmn blue
I also uninstalled and reinstalled sharkive to see if that too could solve it but that was a failure as well

**Comment by SpiredMoth** [comment]
@darkt6 and anyone else coming here trying to add their confirmation about this bug: we know this exists but the Sharkive app will *not* be receiving an update to fix it. We are currently in the middle of merging Sharkive's functionality into [Checkpoint](https://github.com/FlagBrew/Checkpoint).

Until that gets released you'll have to make due with the workaround mentioned in earlier posts of this issue:
1. make sure you have a save file in each of the games that aren't showing up
2. delete `/3ds/Sharkive/titles.sha` (moving or renaming the file also works)

**Comment by BernardoGiordano** [comment]
Closing this as it won't be relevant anymore soon
