### ISSUE TITLE
[Request]Wormhole codes to Ultra Sun/Moon

### ISSUE THREAD

**Issue by Immersion95** [FlagBrew/Sharkive#214]
Would it be possible to add these codes ? I just modified the "Always UB Wormhole" code to get this. I'm sorry but I don't understand how to make a Pull request.

**Titles :**
**00040000001B5000
00040000001B5100**

[Always Red Wormhole v1.2]
002DD36C E3A01001

[Always Blue Wormhole v1.2]
002DD36C E3A01002

[Always Yellow Wormhole v1.2]
002DD36C E3A01003

[Always Green Wormhole v1.2]
002DD36C E3A01004

**00040000001B5100 :**

[Ultra Wormhole Color & Rarity v1.2]
005BBFA0 B5076860
005BBFA4 99054804
005BBFA8 D1044288
005BBFAC 4668210X <- Color X=0:White(UltraBeast), 1:Red, 2:Blue, 3:Yellow, 4:Green
005BBFB0 7701220Y <- Rarity Y=0:Normal, 1:SingleRing, 2:DoubleRing, 3:DoubleAuraRing
005BBFB4 BD077742
005BBFB8 006EAAD0
003FD4F0 FA06FAAA

**00040000001B5000 :**

[Ultra Wormhole Color & Rarity v1.2]
005BBFA0 B5076860
005BBFA4 99054804
005BBFA8 D1044288
005BBFAC 4668210X <- Color X=0:White(UltraBeast), 1:Red, 2:Blue, 3:Yellow, 4:Green
005BBFB0 7701220Y <- Rarity Y=0:Normal, 1:SingleRing, 2:DoubleRing, 3:DoubleAuraRing
005BBFB4 BD077742
005BBFB8 006EAAD0
003FD4EC FA06FAAB

A big thanks to [ymyn](https://gbatemp.net/threads/gateway-cheats.402900/page-169#post-7809299) for the last 2 codes

**Comment by JourneyOver** [comment]
Which ones would be better to add? Guessing the `Ultra Wormhole Color & Rarity v1.2` instead of doing the `always` ones? as if I was to do both it seems like they would just be duplicated of each other minus the whole rarity option for the first ones.

Only issue is if choosing the second `Ultra Wormhole Color & Rarity v1.2` variants it means putting a code for each color/rarity (so literally 20 new codes) as we have to make codes simple enough that end users do not need to go in and edit the codes themselves.

Also have you tested these codes to make sure that they work?

**Comment by Immersion95** [comment]
Hi, yes the codes work.

I think it would be great to add the first [Always COLOR Wormhole v1.2] as there is only the white one present now.

For the rarity, it would be great to only add the highest rarity for each color.

I can post it directly if you prefer.

**Comment by DavidAG2000** [comment]
> Hi, yes the codes work.
> 
> I think it would be great to add the first [Always COLOR Wormhole v1.2] as there is only the white one present now.
> 
> For the rarity, it would be great to only add the highest rarity for each color.
> 
> I can post it directly if you prefer.

It would be cool.

**Comment by NexumN** [comment]
Hey these codes are not working well for me, is there something I might be doing wrong? Which lines am I supposed to replace?

**Comment by Valiumpill** [comment]
Hello!!! Seems that this doesnt work. Or maybe im doing something wrong. Managed to use other codes but these ones. Any idea?

**Comment by anhhongsn** [comment]
Me too, it doesn't work at all
Do you help me ??

**Comment by Lu1X2** [comment]
A few Years later, but you managed to help me get Kyogre man, Thanks alot.
