### ISSUE TITLE
Animal crossing new leaf

### ISSUE THREAD

**Issue by bluesky37** [FlagBrew/Sharkive#219]
cheat Code Animal crossing new leaf 
[L+A for 99k Bells in slot 1]
[L+A all item slots are 99k Bells]
[L+A to clear inv slot 1]
[Item Duplication (L copy, R paste)]
[L+Y/R+Y read/write slot 1 id at ATM]

does not work at all ! Please 
please can you fix them

**Comment by GriffinG1** [comment]
There is an issue template for a reason. Please use it.

**Comment by bluesky37** [comment]
thanks but can you tell me how to use the new model? Should you modify a file in checkpoint ?
