### ISSUE TITLE
No Gyakuten Saiban 4/5/6 cheat for3ds 

### ISSUE THREAD

**Issue by jkclp** [FlagBrew/Sharkive#220]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**:
* **Title ID**:
* **Product code**:
* **Game version**:
* **Luma version**:
* **Atmosphere-NX version**:

### Not working codes

* code 1
* code 2
* ...

**Comment by piepie62** [comment]
Please actually fill out the issue template. Also keep in mind that nobody on the FlagBrew team actually knows how to create codes, so if that was your request, it cannot be filled by us.
