### ISSUE TITLE
issue with code

### ISSUE THREAD

**Issue by raynii12** [FlagBrew/Sharkive#224]
## Issue template

* [] Issue with one or more codes in the database and crashes when I try to use these codes

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3ds
* **Title ID**: story of seasons:trio of towns usa (0019f500)
* **Product code**:
* **Game version**: 1056 (1.2.0)
* **Luma version**: 10.0.1-c913de1
* **Atmosphere-NX version**:

### Not working codes

* [All Outfits]
C0000000 000000A4
20799544 00000007
DC000000 00000008
D2000000 00000000
* [All Hats]
C0000000 00000049
20799AB4 00000007
DC000000 00000008
D2000000 00000000

* [All Glasses]
C0000000 0000001A
20799D54 00000007
DC000000 00000008
D2000000 00000000

**Comment by raynii12** [comment]
i hope i did this alright im new

**Comment by JourneyOver** [comment]
Seems that these codes where made for version 1.0 of the game. I'm not sure how many codes in the .txt file for this game are made for 1.0 and 1.1 but I will at least mark these 3 for the correct version.
