### ISSUE TITLE
Pokemon ORAS and XY

### ISSUE THREAD

**Issue by C-kins** [FlagBrew/Sharkive#226]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3ds
* **Title ID**: 0004000000055D00 (Pokemon X);  0004000000011C500 (Pokemon AS)
* **Product code**:  CTR-P-EKJA (X); CTR-P-ECLA (AS)
* **Game version**: 1.5 (X); 1.4 (AS)
* **Luma version**: 2048 (2.0.0)
* **Atmosphere-NX version**:

### Not working codes

Pokemon X
* (START+L) Wild Pokemon Shiny, (START+R) Disable v1.5
* 100%Catch v1.5

Pokemon AS
* code 154
* code 155
* code 156

I believe that for Alpha Sapphire, codes 154-156 should be in X since the codes say they must be used with the Pokemon Radar which is only found in XY. They do not work at all in Pokemon Alpha Sapphire.

As for Pokemon X, the codes listed turn red when you click on them, so I thought maybe these codes could be switched around.

**Comment by JourneyOver** [comment]
For alpha sapphire and omega ruby (as it exists in both copies) I think those codes are correct, they are just not named correctly. I think it's meant to be for the dexnav stuff but I could be wrong, either way I don't think I'm going to touch those codes at this time.

Codes turning red doesn't mean they are switched around, it could be a number of different things like just the codes being broken or your luma version being out of date (which what you put for luma version is the wrong thing..).

So I will need to know your actual luma version before proceeding with anything. if I don't get a comment back within 7-14 days this issue will be closed without anything done.

**Comment by JourneyOver** [comment]
Closed due to inactivity.
