### ISSUE TITLE
Need help with Demon modifier cheat from SMTIV Apocalypse

### ISSUE THREAD

**Issue by Anonymous5143** [FlagBrew/Sharkive#227]
Citra 3DS - nightly 1599 (HEAD-b94f21e 2020-07-28)
000400000019A200 - Shin Megami Tensei IV Apocalypse (USA)
CTR-BG4E
US - English

Not working codes - [Demon Modifier Up+A]

DD000000 00000041
D3000000 30CF9374
00000004 270F270F
00000008 270F270F
0000000C 270F270F
00000010 270F270F
00000014 270F270F
00000018 270F270F
00000020 270F270F
00000024 270F270F
00000028 270F270F
1000002C 0000270F
00000030 0098967F
10000034 0000012E
10000036 00000132
10000038 0000007A
1000003A 00000068
1000003C 0000006D
1000003E 00000057
10000040 0000005C
10000042 000001E6
00000044 0A0A0A0A
00000048 0A0A0A0A
0000004C 09000900
00000050 09090909
00000054 00090909
00000058 00090009
1000005C 00000009
10000060 00000000
10000062 000000A7
10000064 00000063
D0000000 00000000

Problem: Used the combinations but only creating "Metatron" with all fire skills. Attempt to use this by pressing Up + A button after deleting Metatron but nothing happened, even after restarting the new game & new save file.

I tried using the from the file attached in this. Please help with this issue (つ﹏⊂)

[smtiv_apocalypse_demon_and_skill_hex_editing_info.txt](https://github.com/FlagBrew/Sharkive/files/5029702/smtiv_apocalypse_demon_and_skill_hex_editing_info.txt)

**Comment by GriffinG1** [comment]
We are not going to debug citra issues here, as citra is not the same as original hardware, which the codes are designed for.
