### ISSUE TITLE
Pokemon Ultra Moon Red Cheats

### ISSUE THREAD

**Issue by MoSman29** [FlagBrew/Sharkive#232]
Multiple cheats going red when enabling. Luma up to date. Game version matches version mentioned in the cheat name.

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 001B5100
* **Product code**: CTR-P-A2BA
* **Game version**: v1.2
* **Luma version**: 10.2-bb07a73

### Not working codes

* [1Hit Kill v1.2]
* [Always critical hit v1.2]
* [Camera zoom out(SELECT+L)Enable, (SELECT+R)Disable v1.1 & v1.2]
* [Can throw Pokeball at Trial v1.2]
* [Can use Z-moves multiple times v1.1 & v1.2]
* [Can use mega evolution multiple times in a fight v1.2]
* [HP Not Decrease v1.2]
* [Hold SELECT to view IVs & START to view EVs on Status Screen v1.2]
* [No Encounter, Hold START Instant Encounter v1.1 & v1.2]
* [PP Not Decrease v1.2]

**Comment by M1CR0H4CK3R** [comment]
@JourneyOver I don't know where else to ask this, but are you Vermil from GBAtemp? If so, someone was looking for you there. If not, do you know if he ever posted a commit here? I would like to get ahold of him somehow.

**Comment by JourneyOver** [comment]
@M1CR0H4CK3R ugh no sorry I do not know how to contact him (also I haven't been on GBATemp in a very long time now), also please do not bring off-topic discussions into random issues.
