### ISSUE TITLE
Pokemon Super Mystery Dungeon

### ISSUE THREAD

**Issue by Mr-ZombieSteam** [FlagBrew/Sharkive#236]
Hi,

None of the cheats for SMD work properly, they instantly crash the game. EU version of the game (Cartridge and ROM same issue). 

Platform (3DS/Switch): 3DSXL
Title ID: 0004000000174600
Product code: CTR-P-BPXP
Game version: v1.2
Luma version: 10.2-bb07a73

CHEATS:

$99,999 Money
1st PKMN Max Exp
1st PKMN Max Stats
9999 Gold Bars
Max Team Points

**Comment by JourneyOver** [comment]
As noted here https://github.com/FlagBrew/Sharkive/issues/103#issuecomment-439711202 at least a minimum of one code you wrote not working actually works (the `1st PKMN Max Exp`). The codes are made for game version 1.0 of the game. I should really get around to noting that in this games cheat files..

If you don't mind please re-test all the codes other than the one I wrote above that is confirmed working on game version 1.0

**Comment by Mr-ZombieSteam** [comment]
I'll try now, thanks!

**Comment by Mr-ZombieSteam** [comment]
> As noted here https://github.com/FlagBrew/Sharkive/issues/103#issuecomment-439711202 at least a minimum of one code you wrote not working actually works (the `1st PKMN Max Exp`). The codes are made for game version 1.0 of the game. I should really get around to noting that in this games cheat files..
> 
> 
> 
> If you don't mind please re-test all the codes other than the one I wrote above that is confirmed working on game version 1.0

So I deleted the Update Data and re-enables the cheats. 

$99,999 works, I disabled it after though 

1st PKMN Max Stats works in the dungeon, left the dungeon, walked around a little saved then the game crashed. So I just disabled it after the stat changes, worked a treat. 

Exp also worked, not sure if there's an activation combo, but works in dungeons, again activated, stat changes activated then disabled and saved, all good. 

I need to test gold bars and team points next

**Comment by Mr-ZombieSteam** [comment]
Hi,

This can be closed now. Can't see work if I don't update the game. 

Thanks!
