### ISSUE TITLE
An issue with a code I can't get working.

### ISSUE THREAD

**Issue by inmento** [FlagBrew/Sharkive#241]
So in one part of the faq it reads  

> Q: Some cheats have a star (*) next to their name in Rosalina. Why?
A: This means that the cheat makes use of a key combo. If the cheat name doesn't mention the key combo you'll have to look up the code and translate the line(s) starting DD000000 to figure out what the key combo is.

Translate the lines into what? What code format are they? I'm probably super dumb and don't understand, but perhaps this could be expanded upon, if possible, so that people as dumb as I can understand? 

As for everything you need to know;

System: 3DS (original and not the new if that matters?)
Title Name: Bravely Default (USA)
Title ID: 00040000000FC500
Issue: A semi not working code - Code appears with an * next to it, according to the above quote that means there's a button combo next to it, but in the code list itself one isn't listed and I have no idea how to translate said code to find button combo.
The code itself: [Infinite EXP / Job Points After Battle]
DD000000 00000000

Also no idea if this helps but uh I'm on Luma v10.0.1

**Comment by GriffinG1** [comment]
That is a code that does nothing it seems, as no buttons match with `00000000`, as well as there being nothing else in that code

**Comment by inmento** [comment]
> That is a code that does nothing it seems, as no buttons match with `00000000`, as well as there being nothing else in that code

... So a broken code, that explains so much. Thank you! I don't know how to make codes work for Luma, but I'm sure with some google searches I can easily find out how to convert.
