### ISSUE TITLE
Ultra moon not working cheat code

### ISSUE THREAD

**Issue by sanderkees** [FlagBrew/Sharkive#247]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3ds
* **Title ID**: 00040000001B5100
* **Product code**: Pokémon ultra moon
* **Game version**: 1.2 
* **Luma version**: 10.2.1
* **Atmosphere-NX version**:

### Not working codes

* Can use Z-moves multiple times v1.1 & v1.2

**Comment by GriffinG1** [comment]
Hi, apologies for taking so long to reach out. Can you please elaborate on how this code is not working?

**Comment by GriffinG1** [comment]
Looking further, this code is no longer present in the DB. Closing.
