### ISSUE TITLE
Codes not working

### ISSUE THREAD

**Issue by Rurha** [FlagBrew/Sharkive#248]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3ds
* **Title ID**: 0011C400 
* **Product code**: Pokemon Version Rubis Oméga
* **Game version**: 1.4
* **Luma version**: 10.2.1
* **Atmosphere-NX version**:

### Not working codes

* [(hold R) Walk through Wall 1.4]
* [Walk&run Speedx2 1.4]
* ...

**Comment by GriffinG1** [comment]
Hi, apologies for taking so long to reach out. Can you please elaborate on how these codes are not working?

**Comment by GriffinG1** [comment]
Can confirm these are broken on my side. Will remove from database soon.

**Comment by A4ron-14** [comment]
> ## Issue template
> 
> * [] Issue with one or more codes in the database
> 
> ### Fill this for problems with codes in the database
> 
> * **Platform (3DS/Switch)**: 3ds
> * **Title ID**: 0011C400
> * **Product code**: Pokemon Version Rubis Oméga
> * **Game version**: 1.4
> * **Luma version**: 10.2.1
> * **Atmosphere-NX version**:
> 
> ### Not working codes
> 
> * [(hold R) Walk through Wall 1.4]
> * [Walk&run Speedx2 1.4]
> * ...
