### ISSUE TITLE
Yokai-watch 3 EUR cheat codes

### ISSUE THREAD

**Issue by Zephyr2546** [FlagBrew/Sharkive#252]
* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 00040000001D6900
I use the french version of yokai-watch 3 and i don't succed to add codes from myself or use the ntr Plugin. Can you please add these codes ? You will save me for sure

**Comment by GriffinG1** [comment]
![402A5C58-F00F-401A-BFB7-C2F90E2DD8A1](https://user-images.githubusercontent.com/28538707/103159615-9ec88d80-4788-11eb-8189-57baebaf25fc.jpeg)


Unless you’re saying you’ve already found codes that you want added, but are unsure how to..?

**Comment by Zephyr2546** [comment]
Yes I'm so sorry I'm really a newbie, i find some codes on gbatemp and add them to a .txt file on sd/cheats or sd/luma/titles/00040000001D6900 but they are not detected in the rosalina menu and i don't know why
Sorry for post this in issue i don't succes to create a new pull request

**Comment by Zephyr2546** [comment]
The file weights 8 kb so i think maybe it's not supported but i'm not sure

**Comment by JourneyOver** [comment]
So couple things:

1. As noted by Griffin we don't have anyone on the team who can make codes, so best bet would be to find some codes (which as you noted you have found some) or create them yourself and PR them.
2. If you don't know how to create a PR I would suggest searching google -- here is a quick search already done: https://opensource.com/article/19/7/create-pull-request-github
3. if you are just trying to add the cheats into the correct location on your SD card and not make a PR with them make sure that the folder/file names are correct, and the contents of the file are correct, and that it's in the correct location: https://github.com/LumaTeam/Luma3DS/wiki/Cheat-Engine
4. File size does not matter when it comes to what's supported and what's not.

**Comment by Zephyr2546** [comment]
> So couple things:
> 
> 1. As noted by Griffin we don't have anyone on the team who can make codes, so best bet would be to find some codes (which as you noted you have found some) or create them yourself and PR them.
> 2. If you don't know how to create a PR I would suggest searching google -- here is a quick search already done: https://opensource.com/article/19/7/create-pull-request-github
> 3. if you are just trying to add the cheats into the correct location on your SD card and not make a PR with them make sure that the folder/file names are correct, and the contents of the file are correct, and that it's in the correct location: https://github.com/LumaTeam/Luma3DS/wiki/Cheat-Engine
> 4. File size does not matter when it comes to what's supported and what's not.

Thank you so much for your helpful answer 🙏
