### ISSUE TITLE
CRASHING OR NOT WORKING

### ISSUE THREAD

**Issue by Smoreslickgores** [FlagBrew/Sharkive#258]
When i open it kicks me into my home menu I have Checkpoint installed sooooooooooooo why?

**Comment by raventhecat333** [comment]
same thing for me and it makes a bunch of folders in sd/luma/titles

**Comment by GriffinG1** [comment]
Read the pinned issue in this repo (#179).

**Comment by piepie62** [comment]
Sharkive as an application was deprecated in September 2019. Checkpoint has all its functionality
