### ISSUE TITLE
Digimon World Re-Digitize - Decode  cheats with english patch

### ISSUE THREAD

**Issue by Geo89Pap** [FlagBrew/Sharkive#261]
Um hello i think im doing this wrong but could someone add more codes for the Digimon World Re-Digitize - Decode  with the english patch for 3ds?

**Comment by GriffinG1** [comment]
![image](https://user-images.githubusercontent.com/28538707/111079931-d7dbe880-84c1-11eb-9b1f-14ad575ad324.png)
Straight from the readme.

**Comment by Geo89Pap** [comment]
Hahbme blind ima delete this. Ty
