### ISSUE TITLE
Pokemon Ultra Sun (US) Red Codes

### ISSUE THREAD

**Issue by robloxOBCTBCBC** [FlagBrew/Sharkive#262]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 00040000001B5000
* **Product code**: CTR-P-A2AA
* **Game version**: 1.1
* **Luma version**: 10.2.1
* **Atmosphere-NX version**:

### Not working codes

* No Encounter, Hold START Instant Encounter v1.1
* No Forced Trainer Battles v1.1
* Can use Z-moves multiple times v1.1
* Can throw Pokeball at Trial v1.1
* Can use mega evolution multiple times in a fight v1.1
* Camera zoom out(SELECT+L)Enable, (SELECT+R)Disable v1.1
* PP Not Decrease v1.1
* HP Not Decrease v1.1
* Always critical hit v1.1

**Comment by raventhecat333** [comment]
is this a version conflict?
some codes can only be used at certain times due to the ￼￼memory areas being altered by other￼ lines of code, and if it reads, say byte 0x9f and its currently being written to by the cheat code, it causes an exception and a crash. so to prevent this luma makes it red to warn you.

So it may just of been activated at the wrong time￼￼

**Comment by Mewthree3** [comment]
The [Camera zoom out(SELECT+L)Enable, (SELECT+R)Disable v1.1 & v1.2] one doesn't work for me as well.

**Comment by LKing1337** [comment]
I went through and got rid of any and all red codes not working any longer (v1.2 of US), and pasted a reordered list here for anyone:

drop in root\cheats
[00040000001B5000.txt](https://github.com/FlagBrew/Sharkive/files/7559775/00040000001B5000.txt)
:

**Comment by GriffinG1** [comment]
Hi, apologies for taking so long to reach out. Can you please elaborate on how these codes are not working?

**Comment by GriffinG1** [comment]
Changes regarding this were made via #300 and a472fd8. Assuming issues brought up here have been resolved, you can compile the DB by following the instructions in the README if you want to confirm. Closing as resolved.
