### ISSUE TITLE
[Request] The ability to add codes manually

### ISSUE THREAD

**Issue by USA-RedDragon** [FlagBrew/Sharkive#266]
I'm willing to put in the work to submit a PR, but I'd also like to open an issue to track my work, and enable collaboration at the development stage if anyone wants to contribute.

The idea is to just have a screen that enables you to type in the cheat title, optional details, and the code itself.

One of the problems with this is that some cheats are too long to reasonably input, and my off-the-cuff idea is to allow the codes to be encoded into a QR code to be easily read.

**Comment by GriffinG1** [comment]
This would be a request you'd want to open in [Checkpoint](https://github.com/FlagBrew/Checkpoint/issues]'s repo. Sharkive is *solely* a database.

**Comment by USA-RedDragon** [comment]
Thank you for the clarification. Will do.
