### ISSUE TITLE
Tomodachi Life Cheat Codes have no effect on the Game

### ISSUE THREAD

**Issue by TheDude617** [FlagBrew/Sharkive#273]
Issue with two cheat codes

3DS
000400000008C400
CTR-P-EC6P
Both 1.0 and 2.0
Luma v10.2.1-9189e3d7-3gxldr

50€ L+DOWN v.1.0
MAX MONEY L+UP v.1.0

**Comment by GriffinG1** [comment]
Hi, apologies for taking so long to reach out. Can you please elaborate on how these codes are not working?

**Comment by TheDude617** [comment]
So basically
When attempting the instructions for these Cheats, they don't work, I have
tried every Possible Game Version but they don't work

Griffin ***@***.***> schrieb am Di., 23. Aug. 2022, 06:18:
