### ISSUE TITLE
Please add Yokai Watch Blasters Cheat codes (for both versions, if needed) 

### ISSUE THREAD

**Issue by coltmccoy** [FlagBrew/Sharkive#274]
[Infinite Soultimate v2.3]
003F61F8 E1A00000

 
[Bypass Boss Check v2.3]
003DB198 EA000001
003C73D8 E3A00001
003C73DC E12FFF1E
0049A490 E3A02E19
 
 
[Inf Loop 3-Step Attack v2.3]
00634FD8 E92D4002
00634FDC EBFDD079
00634FE0 E3500000
00634FE4 18BD8002
00634FE8 E2861A01
00634FEC E58102F8
00634FF0 E59D1004
00634FF4 E2411014
00634FF8 E58D1004
00634FFC E8BD8002
004085E0 EB08B27C
 
[Inf HP (SELECT+UP)Enable, (SELECT+DOWN)Disable  v2.3]
00634F98 E5D02720
00634F9C E3520003
00634FA0 CA000004
00634FA4 E598207C
00634FA8 E3520000
00634FAC 0A000001
00634FB0 E5982078
00634FB4 E58026FC
00634FB8 E59016FC
00634FBC E12FFF1E
DD000000 00000044
003D64EC EB097AA9
D0000000 00000000
DD000000 00000084
003D64EC E59016FC
D0000000 00000000
 
[Critical Hit v2.3]
00634F54 E92D4003
00634F58 E2871A01
00634F5C E5D10720
00634F60 E3500003
00634F64 CD9F0A04
00634F68 E597007C
00634F6C E3500000
00634F70 0D9F0A01
00634F74 EE20EA0A
00634F78 E8BD8003
00634F7C 00000000
003CEBE4 EB0998DA
 
[1st Prize Red Cat Corps after mission v2.3]
00634ECC E0860100
00634ED0 E92D40FC
00634ED4 E59D7080
00634ED8 E1A02007
00634EDC EB00000C
00634EE0 E2872010
00634EE4 EB00000A
00634EE8 E2872020
00634EEC EB000008
00634EF0 E2872038
00634EF4 EB000006
00634EF8 E3A05000
00634EFC E0877185
00634F00 E2877008
00634F04 E897000C
00634F08 E881000C
00634F0C E5C15008
00634F10 E8BD80FC
00634F14 E5923008
00634F18 E592400C
00634F1C E5925010
00634F20 E5926014
00634F24 E3530000
00634F28 05825008
00634F2C 0582600C
00634F30 E3550000
00634F34 05823010
00634F38 05824014
00634F3C E12FFF1E
00454200 EB078331
 
[1st Prize White Dog Squad after mission v2.3]
00634ECC E0860100
00634ED0 E92D40FC
00634ED4 E59D7080
00634ED8 E1A02007
00634EDC EB00000C
00634EE0 E2872010
00634EE4 EB00000A
00634EE8 E2872020
00634EEC EB000008
00634EF0 E2872038
00634EF4 EB000006
00634EF8 E3A05001
00634EFC E0877185
00634F00 E2877008
00634F04 E897000C
00634F08 E881000C
00634F0C E5C15008
00634F10 E8BD80FC
00634F14 E5923008
00634F18 E592400C
00634F1C E5925010
00634F20 E5926014
00634F24 E3530000
00634F28 05825008
00634F2C 0582600C
00634F30 E3550000
00634F34 05823010
00634F38 05824014
00634F3C E12FFF1E
00454200 EB078331
 
[2nd Prize Red Cat Corps after mission v2.3]
00634ECC E0860100
00634ED0 E92D40FC
00634ED4 E59D7080
00634ED8 E1A02007
00634EDC EB00000C
00634EE0 E2872010
00634EE4 EB00000A
00634EE8 E2872020
00634EEC EB000008
00634EF0 E2872038
00634EF4 EB000006
00634EF8 E3A05002
00634EFC E0877185
00634F00 E2877008
00634F04 E897000C
00634F08 E881000C
00634F0C E5C15008
00634F10 E8BD80FC
00634F14 E5923008
00634F18 E592400C
00634F1C E5925010
00634F20 E5926014
00634F24 E3530000
00634F28 05825008
00634F2C 0582600C
00634F30 E3550000
00634F34 05823010
00634F38 05824014
00634F3C E12FFF1E
00454200 EB078331
 
[2nd Prize White Dog Squad after mission v2.3]
00634ECC E0860100
00634ED0 E92D40FC
00634ED4 E59D7080
00634ED8 E1A02007
00634EDC EB00000C
00634EE0 E2872010
00634EE4 EB00000A
00634EE8 E2872020
00634EEC EB000008
00634EF0 E2872038
00634EF4 EB000006
00634EF8 E3A05003
00634EFC E0877185
00634F00 E2877008
00634F04 E897000C
00634F08 E881000C
00634F0C E5C15008
00634F10 E8BD80FC
00634F14 E5923008
00634F18 E592400C
00634F1C E5925010
00634F20 E5926014
00634F24 E3530000
00634F28 05825008
00634F2C 0582600C
00634F30 E3550000
00634F34 05823010
00634F38 05824014
00634F3C E12FFF1E
00454200 EB078331
 
[3rd Prize Red Cat Corps after mission v2.3]
00634ECC E0860100
00634ED0 E92D40FC
00634ED4 E59D7080
00634ED8 E1A02007
00634EDC EB00000C
00634EE0 E2872010
00634EE4 EB00000A
00634EE8 E2872020
00634EEC EB000008
00634EF0 E2872038
00634EF4 EB000006
00634EF8 E3A05004
00634EFC E0877185
00634F00 E2877008
00634F04 E897000C
00634F08 E881000C
00634F0C E5C15008
00634F10 E8BD80FC
00634F14 E5923008
00634F18 E592400C
00634F1C E5925010
00634F20 E5926014
00634F24 E3530000
00634F28 05825008
00634F2C 0582600C
00634F30 E3550000
00634F34 05823010
00634F38 05824014
00634F3C E12FFF1E
00454200 EB078331
 
[3rd Prize White Dog Squad after mission v2.3]
00634ECC E0860100
00634ED0 E92D40FC
00634ED4 E59D7080
00634ED8 E1A02007
00634EDC EB00000C
00634EE0 E2872010
00634EE4 EB00000A
00634EE8 E2872020
00634EEC EB000008
00634EF0 E2872038
00634EF4 EB000006
00634EF8 E3A05005
00634EFC E0877185
00634F00 E2877008
00634F04 E897000C
00634F08 E881000C
00634F0C E5C15008
00634F10 E8BD80FC
00634F14 E5923008
00634F18 E592400C
00634F1C E5925010
00634F20 E5926014
00634F24 E3530000
00634F28 05825008
00634F2C 0582600C
00634F30 E3550000
00634F34 05823010
00634F38 05824014
00634F3C E12FFF1E
00454200 EB078331
 
[You didn't Win... after mission v2.3]
00634ECC E0860100
00634ED0 E92D40FC
00634ED4 E59D7080
00634ED8 E1A02007
00634EDC EB00000C
00634EE0 E2872010
00634EE4 EB00000A
00634EE8 E2872020
00634EEC EB000008
00634EF0 E2872038
00634EF4 EB000006
00634EF8 E3A05006
00634EFC E0877185
00634F00 E2877008
00634F04 E897000C
00634F08 E881000C
00634F0C E5C15008
00634F10 E8BD80FC
00634F14 E5923008
00634F18 E592400C
00634F1C E5925010
00634F20 E5926014
00634F24 E3530000
00634F28 05825008
00634F2C 0582600C
00634F30 E3550000
00634F34 05823010
00634F38 05824014
00634F3C E12FFF1E
00454200 EB078331
 
[Special Prize Red Cat Corps after mission v2.3]
00634ECC E0860100
00634ED0 E92D40FC
00634ED4 E59D7080
00634ED8 E1A02007
00634EDC EB00000C
00634EE0 E2872010
00634EE4 EB00000A
00634EE8 E2872020
00634EEC EB000008
00634EF0 E2872038
00634EF4 EB000006
00634EF8 E3A05007
00634EFC E0877185
00634F00 E2877008
00634F04 E897000C
00634F08 E881000C
00634F0C E5C15008
00634F10 E8BD80FC
00634F14 E5923008
00634F18 E592400C
00634F1C E5925010
00634F20 E5926014
00634F24 E3530000
00634F28 05825008
00634F2C 0582600C
00634F30 E3550000
00634F34 05823010
00634F38 05824014
00634F3C E12FFF1E
00454200 EB078331
 
[Special Prize White Dog Squad after mission v2.3]
00634ECC E0860100
00634ED0 E92D40FC
00634ED4 E59D7080
00634ED8 E1A02007
00634EDC EB00000C
00634EE0 E2872010
00634EE4 EB00000A
00634EE8 E2872020
00634EEC EB000008
00634EF0 E2872038
00634EF4 EB000006
00634EF8 E3A05008
00634EFC E0877185
00634F00 E2877008
00634F04 E897000C
00634F08 E881000C
00634F0C E5C15008
00634F10 E8BD80FC
00634F14 E5923008
00634F18 E592400C
00634F1C E5925010
00634F20 E5926014
00634F24 E3530000
00634F28 05825008
00634F2C 0582600C
00634F30 E3550000
00634F34 05823010
00634F38 05824014
00634F3C E12FFF1E
00454200 EB078331

## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**:
* **Title ID**:
* **Product code**:
* **Game version**:
* **Luma version**:
* **Atmosphere-NX version**:

### Not working codes

* code 1
* code 2
* ...

**Comment by GriffinG1** [comment]
Hi, apologies for taking so long to reach out. Can you please confirm these cheats work?

**Comment by NewTab1** [comment]
I have confirmed, these cheats work and they are for that titleID. (Yokai Watch Blasters: Red Cat Corps)

**Comment by JourneyOver** [comment]
Thanks for confirming they still work, I will get them added when I get a chance.

**Comment by Miskyl82** [comment]
Hay algún truco para los orbes rojos? :(

**Comment by Pixelnandez** [comment]
Hi! I'm new on Github and idk how it rlly works.
These cheats are for 3ds or only for emulators? And if it's for emulators, how can i get one? thx :)

**Comment by GriffinG1** [comment]
Please do not comment unrelated questions on closed issues. Join the [FlagBrew Discord](https://discord.gg/bGKEyfY) if you need help.
