### ISSUE TITLE
All Pokémon games 

### ISSUE THREAD

**Issue by Smokey97** [FlagBrew/Sharkive#275]
Add Pokémon event codes. As well as all items and hm and tms. Not sure why they not already in as a code within any of the Pokémon games but they need to be included…..

**Comment by JourneyOver** [comment]
Nobody currently on the FlagBrew team makes cheats. Everything in Sharkive's database comes from user submissions. If you have some working cheats for your game and want them included in Sharkive, submit a pull request and someone will get around to adding them.
