### ISSUE TITLE
Pokemon Y Walk/Run Speed x2

### ISSUE THREAD

**Issue by magatsu64** [FlagBrew/Sharkive#279]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 0004000000055E00
* **Product code**: 
* **Game version**: 1.5
* **Luma version**: 10.2.1
* **Atmosphere-NX version**:

### Not working codes

[Walk&run Speed x2(Only work for D-pad) v1.5]
58092F38 03A05007
08092DE4 13A05003
08092DE8 03A05002
08092F34 13A05005
08092F38 03A05003
D0000000 00000000

**Comment by GriffinG1** [comment]
Hi, apologies for taking so long to reach out. Can you please elaborate on how these codes are not working?

**Comment by GriffinG1** [comment]
Can confirm this code (and the WTW code) does not work. Will remove shortly.
