### ISSUE TITLE
Monster Hunter XX: Double Cross 1.4 cheats

### ISSUE THREAD

**Issue by mechoshira** [FlagBrew/Sharkive#282]
* Please update the cheats for ver. 1.4. [SOURCE](https://gbatemp.net/threads/release-mhxx-1st-2nd-monster-size-mod-plugin.487344/page-4#post-8221353)

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 0004000000197100
* **Product code**: CTR-AGQJ-JPN
* **Game version**: 1.4 (English patch v5)
* **Luma version**: 10.2.1

**Comment by JourneyOver** [comment]
Feel free to open a Pull Request with said codes if you want them included otherwise it might be a while before they get added.

in the meantime I'm going to go ahead and close this issue.
