### ISSUE TITLE
Story of Seasons Trio of Towns - "All Outfits" cheat crashes game 

### ISSUE THREAD

**Issue by brotankfrank** [FlagBrew/Sharkive#283]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 00040000001B5500
* **Product code**: CTR-BB3P
* **Game version**: 1.1 (with DLC installed)
* **Luma version**: 10.2.1
* **Atmosphere-NX version**:

### Not working codes

* code 1 All Outfits 
* code 2
* ...

**Comment by GriffinG1** [comment]
Hi, apologies for taking so long to reach out. Can you please elaborate on how this code is not working?

**Comment by daytimeshootingstar** [comment]
> Hi, apologies for taking so long to reach out. Can you please elaborate on how this code is not working?

hi, im not the topic creator but im also having this issue. when i activate the cheat and enter the closet in my house, i get an arm11 error and the game crashes. will post a luma crash log when im at my PC

**Comment by daytimeshootingstar** [comment]
here ya go [luma crash dump ](https://www.dropbox.com/s/rxzkypv5qmjpr6q/crash_dump_00000002.dmp?dl=0)

**Comment by GriffinG1** [comment]
Hm. The cheat in question is not marked with a version number, it's possible it's made for v1.0

**Comment by daytimeshootingstar** [comment]
maybe. the only other cheats i've tried are the upgrade tool ones and those all work fine. if this is the issue then hopefully someone can make a version of it that works with 1.1

**Comment by JourneyOver** [comment]
I believe Griffin is correct in that assumption. I'll add the version number into the name here soon.

@daytimeshootingstar if you know how to update the cheat database on your own side of things, do you mind testing these here (they should be for 1.1) and tell me if they work:
```
[All Outfits]
C0000000 000000A4
007DC274 00000007
DC000000 00000008
D2000000 00000000

[All Hats]
C0000000 00000047
007DC7E4 00000007
DC000000 00000008
D2000000 00000000

[All Glasses]
C0000000 0000001A
007DCA84 00000007
DC000000 00000008
D2000000 00000000

[Disable All Outfits]
C0000000 000000A4
007DC274 00000000
DC000000 00000008
D2000000 00000000

[Disable All Hats]
C0000000 00000047
007DC7E4 00000000
DC000000 00000008
D2000000 00000000

[Disable All Glasses]
C0000000 0000001A
007DCA84 00000000
DC000000 00000008
D2000000 00000000
```

also from the looks of things every cheat for the game in question doesn't have a version number to it, so they might of all been made during v1.0 and then we just need to figure out which ones still work for v1.1

**Comment by daytimeshootingstar** [comment]
those cheats all work on 1.1 @JourneyOver, thank you very much! no crashes so far :)
