### ISSUE TITLE
pokemon y cheat not working

### ISSUE THREAD

**Issue by Doomslayer900** [FlagBrew/Sharkive#284]
hi im trying to use a cheat but its not working my game is pokemon y on the latest version (1.5)
my luma version is the latest (10.2.1) im trying to use the shiny pokemon cheat but it just doesnt work 
its called (start+l) wild pokemon shiny( start+r) disable v1.5 
6053ED8C E12FFF1E
0053ED80 E5C70004
0053ED84 EA000000
0053ED88 E5C71006
0053ED8C E12FFF1E
D0000000 00000000
580B9338 E5C70004
080B9338 EBF88290
D0000000 00000000
DD000000 00000208
0053ED84 E3A01001
D0000000 00000000
DD000000 00000108
0053ED84 EA000000
D0000000 00000000
please can you help to fix this is super greatful

**Comment by GriffinG1** [comment]
Hi, apologies for taking so long to reach out. Can you please elaborate on how this code is not working?

**Comment by Doomslayer900** [comment]
When activated the name turns red and simply doesn't do anything

**Comment by GriffinG1** [comment]
Can confirm this code does not work. Will remove shortly.
