### ISSUE TITLE
PAD Z Infinite Egg Code not working

### ISSUE THREAD

**Issue by TheHedgehogSonic** [FlagBrew/Sharkive#287]
* Infinite egg code doesn't work.

### Nothing happens when using this code:
C0000000 00000040
281247E8 00000060
DC000000 00000008
D2000000 00000000

Platform 3DS:
* Title ID: 0004000000137700
* Game Version 1.0
* Citra Nightly Version 1740 and 1741

### I should've had 96 of every egg, but instead, the game plays as if nothing happened.

**Comment by GriffinG1** [comment]
Hi. As this bug was discovered on Citra, and not actual hardware, it can't be confirmed as not working. If you can replicate this issue on official hardware (with proof), please let us know and we will remove the code. Thanks.
