### ISSUE TITLE
Pls add Dragon Warrior Monsters I (EU) & II (US) cheat codes

### ISSUE THREAD

**Issue by LarBrun** [FlagBrew/Sharkive#294]
Hello,
sadly there aren't any cheat codes for the gbc games Dragon Warrior Monsters I & II for Checkpoint. Could someone please add some?

**Comment by GriffinG1** [comment]
Directly from the README:
![97D18EC8-7759-44EB-972D-F7EB7692F6CF](https://user-images.githubusercontent.com/28538707/174498720-878438ab-64f5-48f8-9f3c-aeb380191f18.jpeg)
