### ISSUE TITLE
Pokemon Y Refill cheats dont work 

### ISSUE THREAD

**Issue by IvyQuinn-Morrigan** [FlagBrew/Sharkive#301]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: Citra 3DS
* **Title ID**: 0004000000055E00
* **Product code**:
* **Game version**: 1.5
* **Citra version**: Nightly 1788
* **Atmosphere-NX version**:

### Not working codes

[Refill all HP (Press L) v1.5]
DD000000 00000200
481FB284 08200000
481FB624 08200000
B81FB284 00000000
C0000000 00000002
DA000000 0000000E
D7000000 00000010
D3000000 00000000
B81FB624 00000000
D1000000 00000000
D3000000 00000000
B81FB288 00000000
C0000000 00000002
DA000000 0000000E
D7000000 00000010
D3000000 00000000
B81FB628 00000000
D1000000 00000000
D3000000 00000000
B81FB28C 00000000
C0000000 00000002
DA000000 0000000E
D7000000 00000010
D3000000 00000000
B81FB62C 00000000
D1000000 00000000
D3000000 00000000
B81FB290 00000000
C0000000 00000002
DA000000 0000000E
D7000000 00000010
D3000000 00000000
B81FB630 00000000
D1000000 00000000
D3000000 00000000
B81FB294 00000000
C0000000 00000002
DA000000 0000000E
D7000000 00000010
D3000000 00000000
B81FB634 00000000
D1000000 00000000
D3000000 00000000
B81FB298 00000000
C0000000 00000002
DA000000 0000000E
D7000000 00000010
D3000000 00000000
B81FB698 00000000
D1000000 00000000
D3000000 00000000
D2000000 00000000

* 
[Refill HP 5th PKMN (Press L) v1.5]
DD000000 00000200
481FB284 08200000
481FB624 08200000
B81FB294 00000000
DA000000 0000000E
D7000000 00000010
D3000000 00000000
B81FB634 00000000
D7000000 00000010
D2000000 00000000
* ...

**Comment by GriffinG1** [comment]
No guarantees are made for issues found while using Citra. Please only open issues found on original hardware.
