### ISSUE TITLE
Dragon Ball Fusions (3DS) has no cheats? 

### ISSUE THREAD

**Issue by DredgenVayn** [FlagBrew/Sharkive#303]
I have tried to find cheats for Dragon Ball Fusions to unlock the Japanese exclusive characters (Yes, they can be used on other versions, but are locked away due to Japan having an exclusive QR code function). I also was tired of grinding for power orbs, so I had hoped there would be cheats.

Sadly, this isn't the case.

If possible, please can you do something about this?

**Comment by GriffinG1** [comment]
You were already told on discord that nobody on the team knows how to make codes. Find them elsewhere on the internet, or make them, and PR them.
