### ISSUE TITLE
project mirai dx crashing

### ISSUE THREAD

**Issue by dotsunnyy** [FlagBrew/Sharkive#309]
whenever using basically any cheat for project mirai DX through checkpoint it just crashes my 3ds

**Comment by JourneyOver** [comment]
Please update your issue following the issue template, not complying within 7 days will result in this issue being closed without any work being done.

**Comment by JourneyOver** [comment]
Due to you not updating your issue to follow the issue template in a timely manner we will be closing the issue, if you feel like we have made a mistake or you have updated the issue to use the template after closure then feel free to reopen the issue.
