### ISSUE TITLE
Puzzles and Dragons + Super Mario Bros Edition (EU) Super mario bros edition codes not working

### ISSUE THREAD

**Issue by 24KMike** [FlagBrew/Sharkive#311]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 0004000000137800
* **Product code**: Puzzles And Dragons + Super Mario Bros. Edition (EU)
* **Game version**: EU
* **Luma version**: -
* **Atmosphere-NX version**:-

### Not working codes

* code 1: None of the codes on the super mario bros edition work
* code 2: None of the codes on the super mario bros edition work
* ...

**Comment by 24KMike** [comment]
I am on citra and just put the codes in, they don't work

**Comment by JourneyOver** [comment]
> I am on citra and just put the codes in, they don't work

so you are saying you only tested these codes on citra and not on an original 3DS?

**Comment by 24KMike** [comment]
> > I am on citra and just put the codes in, they don't work
> 
> so you are saying you only tested these codes on citra and not on an original 3DS?

Oh, I didn't realise you were still on this project. Sorry for late response, I only tried them on Citra as I don't have a modded 3DS

**Comment by GriffinG1** [comment]
Cheats are only intended for use on official hardware, also piracy is illegal.
