### ISSUE TITLE
Majora mask cheats not working

### ISSUE THREAD

**Issue by whoisupen** [FlagBrew/Sharkive#313]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**:Citra Enhanced beta 2.2
* **Title ID**:0004000000125500
* **Product code**:
* **Game version**:
* **Luma version**:
* **Atmosphere-NX version**:

### Not working codes

* code 1
* code 2
* ...

**Comment by GriffinG1** [comment]
> Platform (3DS/Switch):Citra Enhanced beta 2.2

Cheats are meant to run on original hardware via Luma/Atmosphere. Closing.
