### ISSUE TITLE
Issue Cheats Pokemon Games X/Y

### ISSUE THREAD

**Issue by ForHub-Lou** [FlagBrew/Sharkive#323]
## Issue Cheats Pokemon Games X/Y

* [] All the cheats don't work, some of them make the text red and some of them causes the game to close and restart the 3ds

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 0004000000055D00 (X) / 0004000000055E00 (Y)
* **Product code**: CTR-P-EKJA (X) / CTR-P-EK2A (Y)
* **Game version**: 1.5
* **Luma version**: Luma3DS v13.1.1 

### Not working codes
all (or at least most)

**Comment by ForHub-Lou** [comment]
If you are wondering what error I get, is this

![IMG_20240517_180439](https://github.com/FlagBrew/Sharkive/assets/110502250/261284a2-d340-4bc3-a994-2f02d8dbce01)

**Comment by JourneyOver** [comment]
This is due to a kernel bug. Luma's cheat engine would need to be redesigned to fix this, which would cause another bug elsewhere. As such, there is no solution to this problem at this time besides using another console.
