### ISSUE TITLE
Recheck removed BXXXXXXX codes?

### ISSUE THREAD

**Issue by SpiredMoth** [FlagBrew/Sharkive#73]
With the recent patch to Luma's handling of the `BXXXXXXX` code type (see https://github.com/AuroraWright/Luma3DS/pull/1116), I decided to make a list of games that have had such codes removed so they can potentially be rechecked

- a3c4852
    - `db/0004000000137E00.txt` New Super Mario Bros. 2: Gold Edition (USA)
- d5d185c
    - `db/00040000000AE400.txt` Monster Hunter 3 Ultimate (USA)
- 65a5b46
    - `db/0004000000197100.txt` Monster Hunter XX Double Cross (JPN)
- f5ab051
    - `db/0004000000132700.txt` Mario & Luigi: Paper Jam (USA)
- dfb03cb
    - `db/00040000001D3A00.txt` Bloodstained: Curse of the Moon (JPN)
    - `db/00040000001D4000.txt` Bloodstained: Curse of the Moon (USA)
- fed8c5c
    - `db/00040000001A0400.txt` Super Mario Maker for Nintendo 3DS (USA)
- b261f55
    - `db/0004000000030800.txt` Mario Kart 7 (USA)
- 9097f43
    - `db/0004000000030800.txt` Mario Kart 7 (USA)
    - `db/0004000000187000.txt` Monster Hunter Generations (USA)
- e122f23
    - `db/0004000000049000.txt` Star Fox 64 3D (USA)
- ea79892
    - `db/0004000000054000.txt` Super Mario 3D Land (USA)
- beea6aa
    - `db/000400000007AE00.txt` New Super Mario Bros. 2 (USA)

These last ones may or may not need to be rechecked since they were removed when JourneyOver merged his DB into Sharkive's
- 3e44df6
    - `db/0004000000030800.txt` Mario Kart 7 (USA)
    - `db/00040000000D5A00.txt` Mario & Luigi: Dream Team (USA)

**Comment by JourneyOver** [comment]
Thanks for compiling this list ^^ I have a few of these games myself so when I get time I'll probably recheck some of them myself, unless of course someone else comes along and rechecks them all before me.

**Comment by piepie62** [comment]
Related to this issue: might want to check CTRPF-AR extended codes. I'm not nearly as helpful in providing a list (I don't even know how that was done, to be quite honest), but with my recent changes to Luma, those might work

**Comment by SpiredMoth** [comment]
I just worked backwards through the commit history, from the latest to when Journey had merged the changes from his other repo into Sharkive's DB, checking for removed lines beginning with `BXXXXXXX` and noting each game that had one (or more)

**Comment by BernardoGiordano** [comment]
I think this can be closed now
