### ISSUE TITLE
Max Money Cheat Doesn't Work(Xenoblade Chronicles 3D)

### ISSUE THREAD

**Issue by Burningocean2012** [FlagBrew/Sharkive#81]
## Issue template

* [] Issue with Sharkive
* [] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**:000400000F700100
* **Product code**:CTR-CAFE
* **Game version**:1.1

### Not working codes

* code 1
[Max Money v1.1]
604C69A0 00000000
B04C69A0 00000000
000120E8 3B9AC9FF
D2000000 00000000

* code 2
* ...

**Comment by JourneyOver** [comment]
Can you please test with latest Luma nightly.

**Comment by Burningocean2012** [comment]
I was able to test the code with Luma 9.1 stable and now it works perfectly.I'm not sure if the code got updated or something I did made it work today.

**Comment by JourneyOver** [comment]
Well I can say that it was probably something on your end as the DB hasn't been updated in 14 days so no codes have been updated or anything.

Anyways since it's working I'm going to close this issue.
