### ISSUE TITLE
[USA] RyanmFisher Cheat code testing

### ISSUE THREAD

**Issue by RyanmFisher** [FlagBrew/Sharkive#82]
I will be testing codes for many games starting here with Captain Toad I will be using luma Ver 9.1-3903ac64 currently the latest nightly 

**Not **Working****
Always Have Hammer (Freeze)
The rest (Inconsistent sometimes freezes)

**Comment by JourneyOver** [comment]
I can assure you that captain toad codes work, as I have used them myself when messing around with the game.

**Comment by JourneyOver** [comment]
Just making sure that you are still doing this?? Otherwise I'm going to close this issue as the only cheats you have reported so far actually work.

**Comment by RyanmFisher** [comment]
might be best to close it I have not have much time recently sorry

**Comment by JourneyOver** [comment]
Alright I'll close this issue then.
