### ISSUE TITLE
Nintendogs + Cats Golden Retriever 

### ISSUE THREAD

**Issue by MudkipBanana** [FlagBrew/Sharkive#84]
## Issue template

* [x] Issue with Sharkive
* [] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behavior**: Loads Nintendogs+Cats Golden Retriever with save data in database and displays it in the top screen
* **Encountered behavior**: Doesn't load game at all

### Fill this for problems with codes in the database

* **Title ID**:0004000000030D00
* **Product code**:CTR-P-ADAE (thats what FBI says)
* **Game version**:0 (0.0.0) (thats what FBI says)

### Not working codes

* code 1
* code 2
* ...

**Comment by SpiredMoth** [comment]
There's a known bug ( #21 ) where Sharkive doesn't properly refresh the title list after saves are made in new games. Try deleting `titles.sha` from the Sharkive folder and see if that fixes your problem

**Comment by MudkipBanana** [comment]
should I delete it or move it? I dont know if I need that file

**Comment by SpiredMoth** [comment]
No need to keep it unless you want to revert back to that incomplete list of found games

**Comment by JourneyOver** [comment]
Is this issue fixed? @MudkipBanana if so either close this issue or let me know if it is please and I will close this.
