### ISSUE TITLE
Fire Emblem Awakening Codes Paragon and Limit Breaker Do Nothing?

### ISSUE THREAD

**Issue by Quantum-64** [FlagBrew/Sharkive#85]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**:00040000000A0500
* **Product code**:CTR-P-AFEE (according to FBI)
* **Game version**: 0.0.0 (according to FBI)

### Not working codes

*  Paragon
*  Limit Breaker

**Comment by JourneyOver** [comment]
Can you please test with the latest Luma nightly and let me know if they are still broken.

**Comment by Quantum-64** [comment]
> Can you please test with the latest Luma nightly and let me know if they are still broken.

Im fairly sure I am I could try again.
