### ISSUE TITLE
No Codes for Animal Crossing:New Leaf USA

### ISSUE THREAD

**Issue by theyellingmute** [FlagBrew/Sharkive#86]
### Fill this for problems with codes in the database

* **0004000000198E00**:
* **2301**:
* **IDK how to check but im using the catridge so its the most up to date**:

### Not working codes
None available

not sure if this should be posted as an issue, maybe none exist for the game? idk but i felt since i couldnt find any i should post an issue just in case someone could add them.

**Comment by JourneyOver** [comment]
Not a valid issue, codes may not be available for all games. Codes may or may not be added for a game at any time.
