### ISSUE TITLE
Smash 3DS Cheats Not Working

### ISSUE THREAD

**Issue by Link5261** [FlagBrew/Sharkive#87]
## Issue template
* [√] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**: 00040000000EDF00
* **Product code**: CTR-P-AXCE
* **Game version**: 2080 (2.2.0)

### Not working codes

* [99 lives in solo Classic/All-Star mode]
* [All trophies x99]
* [All Star mode 0% - press "R"]
* [Infinite Lives in Solo/Group]
* [255 customizations from Trophy Rush]
* [Press L for 9,999,999 Gold v1.4 Old3ds]
* [Press L for 9,999,999 Gold v1.1.3 Old3...] (truncated)

**Comment by JourneyOver** [comment]
I can't remember if you said it in discord or not as it's been a while but was this done with Luma nightly?

**Comment by Link5261** [comment]
Yes, at the time of testing, I attempted both the standard and nightly
builds for Luma.

**Comment by JourneyOver** [comment]
Okay great thanks

**Comment by Daega** [comment]
What does character modifier mean and how does it work?

**Comment by JourneyOver** [comment]
it's something that I should probably remove, due to the fact that it requires the user to edit the cheat.txt file, which going by past interactions is very hard for some users to comprehend on how to do.
