### ISSUE TITLE
ACNL (EUR) codes not working

### ISSUE THREAD

**Issue by LizMorphine** [FlagBrew/Sharkive#92]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**: 
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 0008640
* **Product code**: CTR-P-EGDP
* **Game version**: 3072 (3.0.0)
* **Media Type**: Game card

### Not working codes
None of them

I have the latest stable version of Luma (9.1)

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as has several fixes for cheat compatibility, if the codes continue to not work then please let me know.

Thank you!

**Comment by JourneyOver** [comment]
Due to no reply on if you had/have tested the codes with Luma nightly for the past week, this issue will be closed.

If you feel that this is a mistake or you end up updating this issue to comment about testing with Luma nightly then feel free to reopen the issue.
