### ISSUE TITLE
Ocarina of Time 3D Report

### ISSUE THREAD

**Issue by CptDinosaur** [FlagBrew/Sharkive#97]
## Issue template

* [ ] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**: 0004000000033500
* **Product code**: CTR-P-AQEE
* **Game version**: Latest (idk where to find it)
* **Luma version**: 9.1-bd15f51 (Nightly)

### Not working codes
* Hookshot and Longshot Have Much Longer... (Cuts off)

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by JourneyOver** [comment]
Okay thanks for the report.
