### ISSUE TITLE
Mario Kart 7 Report

### ISSUE THREAD

**Issue by CptDinosaur** [FlagBrew/Sharkive#99]
## Issue template

* [ ] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**: 0004000000030800
* **Product code**: CTR-P-AMKE
* **Game version**: Latest (idk where to find it)
* **Luma version**: 9.1-bd15f51 (Nightly)

### Not working codes
* Item Cycler Rev0 v.1.1
* Instant Respawn
* Infinite Balloons
* Battle Points Controller
* Total Laps Amount Modifier
* The Stalking Hack
* Moonjump
* Coins Modifier
* Allow Front-face clipping
* Disable Speed Boosts rev0
* Disable Speed Boosts rev1
* Grand Prix Points Modifier

**Comment by CptDinosaur** [comment]
Updated for Nightly, some are fixed, but there's one extra

**Comment by JourneyOver** [comment]
Thanks for the report.

**Comment by JourneyOver** [comment]
Sadlg I wasn't able to get to this issue in time before I had to leave, will work on this issue either whenever I get my computer or the next time I get access to a computer again.
